#!/usr/bin/env bash
# Idempotent WordPress sandbox bootstrap for the end-to-end theme test.
#
# Downloads a fresh WordPress + the SQLite drop-in into $WPB_E2E_DIR
# (default /tmp/wpb-e2e/wp), wires wp-config.php for SQLite, and runs
# the WordPress installer so the site is ready to receive a theme.
#
# Re-running this script is a no-op once the site is installed; pass
# WPB_E2E_FRESH=1 to wipe and reinstall from scratch.
set -euo pipefail

WP_DIR="${WPB_E2E_DIR:-/tmp/wpb-e2e/wp}"
WP_VERSION="${WPB_E2E_WP_VERSION:-latest}"
SQLITE_PLUGIN_REF="${WPB_E2E_SQLITE_REF:-main}"

if [[ "${WPB_E2E_FRESH:-0}" = "1" ]]; then
  rm -rf "$WP_DIR"
fi

mkdir -p "$(dirname "$WP_DIR")"

if [[ ! -f "$WP_DIR/wp-load.php" ]]; then
  echo "[setup-wp] downloading WordPress ${WP_VERSION}..."
  tmp="$(mktemp -d)"
  curl -fsSL "https://wordpress.org/${WP_VERSION}.tar.gz" -o "$tmp/wp.tar.gz"
  tar -xzf "$tmp/wp.tar.gz" -C "$tmp"
  mkdir -p "$WP_DIR"
  cp -a "$tmp/wordpress/." "$WP_DIR/"
  rm -rf "$tmp"
fi

PLUGIN_DIR="$WP_DIR/wp-content/plugins/sqlite-database-integration"
if [[ ! -d "$PLUGIN_DIR" ]]; then
  echo "[setup-wp] downloading sqlite-database-integration..."
  tmp="$(mktemp -d)"
  curl -fsSL "https://github.com/WordPress/sqlite-database-integration/archive/${SQLITE_PLUGIN_REF}.tar.gz" -o "$tmp/sqlite.tar.gz"
  tar -xzf "$tmp/sqlite.tar.gz" -C "$tmp"
  src="$(find "$tmp" -maxdepth 1 -type d -name 'sqlite-database-integration*' | head -n1)"
  mkdir -p "$PLUGIN_DIR"
  cp -a "$src/." "$PLUGIN_DIR/"
  rm -rf "$tmp"
fi

# Drop-in: tells WordPress to use SQLite instead of MySQL.
if [[ ! -f "$WP_DIR/wp-content/db.php" ]]; then
  cp "$PLUGIN_DIR/db.copy" "$WP_DIR/wp-content/db.php"
  # The drop-in template references {SQLITE_IMPLEMENTATION_FOLDER_PATH} and
  # {SQLITE_PLUGIN}; substitute with absolute paths for our sandbox.
  php -r '
    $p = $argv[1];
    $s = file_get_contents($p);
    $s = str_replace("{SQLITE_IMPLEMENTATION_FOLDER_PATH}", $argv[2] . "/wp-includes/sqlite", $s);
    $s = str_replace("{SQLITE_PLUGIN}", "sqlite-database-integration/load.php", $s);
    file_put_contents($p, $s);
  ' "$WP_DIR/wp-content/db.php" "$WP_DIR"
fi

if [[ ! -f "$WP_DIR/wp-config.php" ]]; then
  cat > "$WP_DIR/wp-config.php" <<PHP
<?php
// Generated by setup-wp.sh for the WP Bridge AI end-to-end test.
define('DB_NAME', 'wordpress');
define('DB_USER', 'root');
define('DB_PASSWORD', '');
define('DB_HOST', 'localhost');
define('DB_CHARSET', 'utf8');
define('DB_COLLATE', '');
define('DATABASE_TYPE', 'sqlite');
define('DB_DIR', __DIR__ . '/wp-content/database/');
define('DB_FILE', '.ht.sqlite');

\$table_prefix = 'wp_';

define('AUTH_KEY',         'wpb-e2e-key');
define('SECURE_AUTH_KEY',  'wpb-e2e-key');
define('LOGGED_IN_KEY',    'wpb-e2e-key');
define('NONCE_KEY',        'wpb-e2e-key');
define('AUTH_SALT',        'wpb-e2e-salt');
define('SECURE_AUTH_SALT', 'wpb-e2e-salt');
define('LOGGED_IN_SALT',   'wpb-e2e-salt');
define('NONCE_SALT',       'wpb-e2e-salt');

define('WP_DEBUG', true);
define('WP_DEBUG_LOG', __DIR__ . '/wp-content/debug.log');
define('WP_DEBUG_DISPLAY', false);
define('AUTOMATIC_UPDATER_DISABLED', true);
define('DISALLOW_FILE_MODS', true);

if ( ! defined('ABSPATH') ) {
    define('ABSPATH', __DIR__ . '/');
}
require_once ABSPATH . 'wp-settings.php';
PHP
fi

# Run the installer once. The presence of the SQLite DB file means installed.
DB_PATH="$WP_DIR/wp-content/database/.ht.sqlite"
if [[ ! -f "$DB_PATH" ]]; then
  echo "[setup-wp] running WordPress installer..."
  mkdir -p "$WP_DIR/wp-content/database"
  php "$(dirname "$0")/install-wp.php" "$WP_DIR"
fi

echo "[setup-wp] WordPress ready at $WP_DIR"
