import AdmZip from "adm-zip";
import path from "node:path";
import type { ExtractedSection, ExtractedPage } from "./sectionFieldExtractor";

interface ThemeInput {
  projectName: string;
  projectSlug: string;       // theme dir name, lowercase-dashed
  combinedCss: string;
  combinedJs: string;
  pages: ExtractedPage[];
  sourceZip: Buffer | null;  // original ZIP — we copy images/fonts into the theme
}

const STYLE_HEADER = (name: string, slug: string) => `/*
Theme Name: ${name} (Pixel-Perfect)
Theme URI: https://wpbridgeai.com
Author: WP Bridge AI
Description: Auto-generated child theme for ${name}. Renders the original design pixel-for-pixel via custom Gutenberg blocks and Elementor widgets.
Version: 1.0.0
Text Domain: ${slug}
*/
`;

const INDEX_PHP = `<?php
get_header();
if ( have_posts() ) :
  while ( have_posts() ) : the_post();
    the_content();
  endwhile;
endif;
get_footer();
`;

const HEADER_PHP = `<!doctype html>
<html <?php language_attributes(); ?>>
<head>
<meta charset="<?php bloginfo( 'charset' ); ?>">
<meta name="viewport" content="width=device-width, initial-scale=1">
<?php wp_head(); ?>
</head>
<body <?php body_class(); ?>>
`;

const FOOTER_PHP = `<?php wp_footer(); ?>
</body></html>
`;

// Dedicated page template — WordPress prefers page.php over index.php for
// pages, and Elementor's content rendering also expects this template to
// exist on a fully-fledged child theme.
const PAGE_PHP = `<?php
get_header();
while ( have_posts() ) : the_post();
    the_content();
endwhile;
get_footer();
`;

// Optional dedicated wiring file for Elementor widget registration. The
// main functions.php already has the same hook, but we also expose this
// file as the canonical place to override widget behaviour without editing
// functions.php itself.
const ELEMENTOR_WIDGETS_INC = `<?php
/**
 * Elementor widget wiring for the generated theme. This file is included
 * by functions.php after the base widget class is loaded. Custom widget
 * tweaks (icons, controls, categories) belong here.
 */
if ( ! defined( 'ABSPATH' ) ) exit;

add_action( 'elementor/elements/categories_registered', function ( $elements_manager ) {
    $elements_manager->add_category(
        'wpb-' . WPB_THEME_SLUG,
        array( 'title' => WPB_THEME_SLUG, 'icon' => 'fa fa-puzzle-piece' )
    );
} );
`;

const FUNCTIONS_PHP_TEMPLATE = (slug: string, blockNames: string[]) => `<?php
/**
 * ${slug} — generated by WP Bridge AI.
 * Enqueues the original template's CSS/JS and registers per-section blocks.
 */
if ( ! defined( 'ABSPATH' ) ) exit;

define( 'WPB_THEME_SLUG', '${slug}' );
define( 'WPB_THEME_DIR', get_stylesheet_directory() );
define( 'WPB_THEME_URI', get_stylesheet_directory_uri() );

add_action( 'wp_enqueue_scripts', function () {
    wp_enqueue_style( 'wpb-theme-style', WPB_THEME_URI . '/style.css', array(), '1.0.0' );
    wp_enqueue_style( 'wpb-template-css', WPB_THEME_URI . '/assets/template.css', array(), '1.0.0' );
    if ( file_exists( WPB_THEME_DIR . '/assets/template.js' ) ) {
        wp_enqueue_script( 'wpb-template-js', WPB_THEME_URI . '/assets/template.js', array( 'jquery' ), '1.0.0', true );
    }
}, 100 );

/**
 * Register every per-section block by reading its block.json + render.php.
 * Each block's render.php substitutes typed placeholders ({{TEXT:k}},
 * {{URL:k}}, {{ATTR:k}}) with the block's attribute values.
 */
add_action( 'init', function () {
    $blocks_dir = WPB_THEME_DIR . '/blocks';
    if ( ! is_dir( $blocks_dir ) ) return;
    foreach ( scandir( $blocks_dir ) as $entry ) {
        if ( $entry === '.' || $entry === '..' ) continue;
        $block_path = $blocks_dir . '/' . $entry;
        if ( is_dir( $block_path ) && file_exists( $block_path . '/block.json' ) ) {
            register_block_type( $block_path );
        }
    }
} );

/**
 * Render helper used by every block. Loads the template, performs typed
 * substitutions, and returns the resulting HTML.
 */
function wpb_render_section_template( string $template_path, array $attrs ): string {
    if ( ! file_exists( $template_path ) ) return '';
    $tpl = file_get_contents( $template_path );
    // First pass: rebase any {{THEME_URI}} placeholders to the actual child theme URL.
    // Field defaults that came from the original HTML's relative asset paths (images,
    // CSS backgrounds, etc.) also use this placeholder so they keep working when the
    // user edits and re-saves them.
    $theme_uri = esc_url( get_stylesheet_directory_uri() );
    $tpl = str_replace( '{{THEME_URI}}', $theme_uri, $tpl );
    foreach ( $attrs as $k => $v ) {
        if ( is_string( $v ) && strpos( $v, '{{THEME_URI}}' ) !== false ) {
            $attrs[ $k ] = str_replace( '{{THEME_URI}}', $theme_uri, $v );
        }
    }
    $rendered = preg_replace_callback(
        '/\\{\\{(TEXT|ATTR|URL|TAG):([A-Za-z0-9_]+)\\}\\}/',
        function ( $m ) use ( $attrs ) {
            $val = $attrs[ $m[2] ] ?? '';
            if ( ! is_string( $val ) ) $val = (string) $val;
            switch ( $m[1] ) {
                case 'TEXT': return esc_html( $val );
                case 'ATTR': return esc_attr( $val );
                case 'URL':  return esc_url( $val );
                case 'TAG':  return preg_match( '/^h[1-6]$/', $val ) ? $val : 'h2';
            }
            return '';
        },
        $tpl
    ) ?? '';
    // Heading tag-swap pass: any element marked with data-wpb-tag="key"
    // gets its open/close tag rewritten to whichever h1-h6 the saved field
    // value asks for. We only touch h1-h6 elements so other markup stays
    // intact, and we sanitise the target tag against the same allowlist.
    $rendered = preg_replace_callback(
        '/<(h[1-6])([^>]*?)\\sdata-wpb-tag="([A-Za-z0-9_]+)"([^>]*)>(.*?)<\\/\\1>/is',
        function ( $m ) use ( $attrs ) {
            $orig = $m[1];
            $key  = $m[3];
            $next = isset( $attrs[ $key ] ) && is_string( $attrs[ $key ] ) ? $attrs[ $key ] : $orig;
            if ( ! preg_match( '/^h[1-6]$/', $next ) ) $next = $orig;
            $rest_attrs = trim( $m[2] . ' ' . $m[4] );
            $rest_attrs = preg_replace( '/\\sdata-wpb-tag="[^"]*"/', '', ' ' . $rest_attrs );
            $rest_attrs = trim( $rest_attrs );
            $open_attrs = $rest_attrs === '' ? '' : ' ' . $rest_attrs;
            return '<' . $next . $open_attrs . '>' . $m[5] . '</' . $next . '>';
        },
        $rendered
    ) ?? $rendered;
    return $rendered;
}

/**
 * Register Elementor widgets if Elementor is active. Each widget mirrors a
 * per-section block: same fields, same template substitution, so the user
 * can edit either inside Gutenberg or inside Elementor.
 */
// Optional Elementor wiring overrides — registers a category etc.
if ( file_exists( WPB_THEME_DIR . '/inc/elementor-widgets.php' ) ) {
    require_once WPB_THEME_DIR . '/inc/elementor-widgets.php';
}

add_action( 'elementor/widgets/register', function ( $widgets_manager ) {
    $widgets_dir = WPB_THEME_DIR . '/widgets';
    if ( ! is_dir( $widgets_dir ) ) return;
    require_once WPB_THEME_DIR . '/widgets/_base-widget.php';
    foreach ( glob( $widgets_dir . '/widget-*.php' ) as $widget_file ) {
        require_once $widget_file;
        // Generated widget files are named widget-<safeDir>.php and the class
        // inside is WPB_Widget_<safeDir-with-dashes-replaced-by-underscores>.
        // Strip the 'widget-' prefix FIRST, then normalise.
        $base  = preg_replace( '/^widget-/', '', basename( $widget_file, '.php' ) );
        $class = 'WPB_Widget_' . preg_replace( '/[^a-zA-Z0-9_]/', '_', $base );
        if ( class_exists( $class ) ) {
            $widgets_manager->register( new $class() );
        }
    }
} );
`;

const ELEMENTOR_BASE_WIDGET = `<?php
if ( ! defined( 'ABSPATH' ) ) exit;
if ( ! class_exists( 'WPB_Widget_Base' ) && class_exists( '\\\\Elementor\\\\Widget_Base' ) ) {
class WPB_Widget_Base extends \\Elementor\\Widget_Base {
    protected $wpb_id = '';
    protected $wpb_label = '';
    protected $wpb_template_path = '';
    protected $wpb_fields = array();
    protected $wpb_groups = array();

    public function get_name() { return 'wpb_' . $this->wpb_id; }
    public function get_title() { return $this->wpb_label; }
    public function get_icon() { return 'eicon-section'; }
    public function get_categories() { return array( 'general' ); }

    /**
     * Map our control type tag to Elementor's Controls_Manager constant.
     * The CHOOSE control is rendered as a SELECT for compactness; for
     * heading tag pickers we surface the h1-h6 options on the same row.
     */
    private function wpb_control_type( $type ) {
        switch ( $type ) {
            case 'textarea': return \\Elementor\\Controls_Manager::TEXTAREA;
            case 'url':      return \\Elementor\\Controls_Manager::URL;
            case 'media':    return \\Elementor\\Controls_Manager::MEDIA;
            case 'choose':   return \\Elementor\\Controls_Manager::SELECT;
            case 'text':
            default:         return \\Elementor\\Controls_Manager::TEXT;
        }
    }

    protected function register_controls() {
        // Preferred path: walk the semantic groups[] and emit one
        // start_controls_section per element (Button, Image, Heading...).
        // Falls back to the old flat fields[] list when groups are empty
        // (legacy theme upgrade path).
        if ( is_array( $this->wpb_groups ) && count( $this->wpb_groups ) > 0 ) {
            foreach ( $this->wpb_groups as $g ) {
                $section_id = 'wpb_grp_' . preg_replace( '/[^a-zA-Z0-9_]/', '_', $g['id'] ?? 'g' );
                $this->start_controls_section( $section_id, array(
                    'label' => esc_html( $g['label'] ?? 'Section' ),
                    'tab'   => \\Elementor\\Controls_Manager::TAB_CONTENT,
                ) );
                foreach ( ($g['controls'] ?? array()) as $c ) {
                    $type = $this->wpb_control_type( $c['type'] ?? 'text' );
                    $args = array(
                        'label'       => esc_html( $c['label'] ?? $c['key'] ),
                        'type'        => $type,
                        'label_block' => true,
                    );
                    if ( $type === \\Elementor\\Controls_Manager::URL ) {
                        $args['default'] = array(
                            'url'         => $c['default'] ?? '',
                            'is_external' => false,
                            'nofollow'    => false,
                        );
                    } elseif ( $type === \\Elementor\\Controls_Manager::MEDIA ) {
                        $args['default'] = array(
                            'url' => $c['default'] ?? '',
                        );
                    } elseif ( $type === \\Elementor\\Controls_Manager::SELECT ) {
                        $opts = isset( $c['options'] ) && is_array( $c['options'] ) ? $c['options'] : array();
                        $args['options'] = array_combine( $opts, $opts );
                        $args['default'] = $c['default'] ?? ( $opts[0] ?? '' );
                    } else {
                        $args['default'] = $c['default'] ?? '';
                    }
                    $this->add_control( $c['key'], $args );
                }
                $this->end_controls_section();
            }
            return;
        }

        $this->start_controls_section( 'content', array(
            'label' => esc_html__( 'Content', 'wpb' ),
            'tab'   => \\Elementor\\Controls_Manager::TAB_CONTENT,
        ) );
        foreach ( $this->wpb_fields as $f ) {
            $type = $f['type'] === 'text' && strlen( $f['default'] ?? '' ) > 80
                ? \\Elementor\\Controls_Manager::TEXTAREA
                : \\Elementor\\Controls_Manager::TEXT;
            $this->add_control( $f['key'], array(
                'label'   => esc_html( $f['label'] ?? $f['key'] ),
                'type'    => $type,
                'default' => $f['default'] ?? '',
            ) );
        }
        $this->end_controls_section();
    }

    /**
     * Reduce the Elementor settings array (which uses structured shapes
     * for URL / MEDIA controls) down to the flat scalar map the template
     * renderer expects. Each control's value lands at $attrs[$fieldKey],
     * keyed by whatever placeholder ({{TEXT:k}}, {{URL:k}}, ...) the
     * template uses.
     */
    private function wpb_settings_to_attrs( $settings ) {
        $attrs = array();
        if ( ! is_array( $this->wpb_groups ) ) return $settings;
        foreach ( $this->wpb_groups as $g ) {
            foreach ( ($g['controls'] ?? array()) as $c ) {
                $ck  = $c['key'] ?? '';
                $fk  = $c['fieldKey'] ?? $ck;
                $val = $settings[ $ck ] ?? ( $c['default'] ?? '' );
                $type = $c['type'] ?? 'text';
                if ( $type === 'url' && is_array( $val ) ) {
                    $val = isset( $val['url'] ) ? (string) $val['url'] : '';
                } elseif ( $type === 'media' && is_array( $val ) ) {
                    $val = isset( $val['url'] ) ? (string) $val['url'] : '';
                } else {
                    $val = is_string( $val ) ? $val : (string) $val;
                }
                $attrs[ $fk ] = $val;
            }
        }
        return $attrs;
    }

    protected function render() {
        $settings = $this->get_settings_for_display();
        $attrs    = is_array( $this->wpb_groups ) && count( $this->wpb_groups ) > 0
            ? $this->wpb_settings_to_attrs( $settings )
            : $settings;
        echo wpb_render_section_template( WPB_THEME_DIR . '/' . $this->wpb_template_path, $attrs );
    }
}
}
`;

function blockJsonFor(slug: string, section: ExtractedSection): string {
  const attributes: Record<string, { type: string; default: string }> = {};
  for (const f of section.fields) {
    attributes[f.key] = { type: "string", default: f.default };
  }
  return JSON.stringify(
    {
      $schema: "https://schemas.wp.org/trunk/block.json",
      apiVersion: 3,
      name: section.blockName,
      version: "1.0.0",
      title: section.label,
      category: "widgets",
      icon: "layout",
      description: `Pixel-perfect section from ${slug}`,
      keywords: [slug, section.category],
      supports: { html: false, align: ["wide", "full"] },
      attributes,
      // Server-rendered with a shared editor script that auto-generates
      // an InspectorControls panel from the attribute schema.
      editorScript: "file:../../assets/editor.js",
      render: "file:./render.php",
      textdomain: slug,
    },
    null,
    2,
  );
}

/**
 * Shared Gutenberg editor script: for every block whose name starts with
 * `wpb-${projectSlug}/`, replace its edit() with a server-side preview
 * component plus an InspectorControls panel that shows one TextControl /
 * TextareaControl per attribute. Saves remain server-rendered (the
 * register from PHP wins on save_post). This satisfies the requirement
 * that all extracted text/url/attr fields are editable inside Gutenberg.
 */
const EDITOR_JS = (slug: string) => `(function(){
    var prefix = 'wpb-${slug}/';
    var el = wp.element.createElement;
    var SSR = wp.serverSideRender;
    var Fragment = wp.element.Fragment;
    var InspectorControls = wp.blockEditor && wp.blockEditor.InspectorControls;
    var PanelBody = wp.components.PanelBody;
    var TextControl = wp.components.TextControl;
    var TextareaControl = wp.components.TextareaControl;
    var useBlockProps = wp.blockEditor.useBlockProps || function(){ return {}; };

    function makeEdit(blockName, attrSchema){
      return function Edit(props){
        var atts = props.attributes || {};
        var controls = Object.keys(attrSchema).map(function(key){
          var val = atts[key] !== undefined ? atts[key] : (attrSchema[key].default || '');
          var Comp = (typeof val === 'string' && val.length > 80) ? TextareaControl : TextControl;
          return el(Comp, {
            key: key,
            label: key,
            value: val,
            onChange: function(next){
              var u = {}; u[key] = next; props.setAttributes(u);
            }
          });
        });
        return el(Fragment, {},
          InspectorControls && el(InspectorControls, {},
            el(PanelBody, { title: 'Section content', initialOpen: true }, controls)
          ),
          el('div', useBlockProps(),
            el(SSR, { block: blockName, attributes: atts })
          )
        );
      };
    }

    wp.domReady(function(){
      var types = wp.blocks.getBlockTypes().filter(function(t){ return t.name && t.name.indexOf(prefix) === 0; });
      types.forEach(function(t){
        wp.blocks.unregisterBlockType(t.name);
        wp.blocks.registerBlockType(t.name, Object.assign({}, t, {
          edit: makeEdit(t.name, t.attributes || {}),
          save: function(){ return null; }
        }));
      });
    });
})();
`;

function blockRenderPhp(section: ExtractedSection, blockDirRel: string): string {
  return `<?php
/**
 * Render: ${section.label}
 * Auto-generated by WP Bridge AI. Do not hand-edit — regenerate the theme
 * if the source HTML structure changes.
 */
$attrs = isset( $attributes ) && is_array( $attributes ) ? $attributes : array();
echo wpb_render_section_template( __DIR__ . '/template.html', $attrs );
`;
}

function widgetPhpFor(section: ExtractedSection, templateRelPath: string): string {
  const safeId = section.blockName.split("/")[1].replace(/[^a-zA-Z0-9_]/g, "_");
  const fieldsJson = JSON.stringify(section.fields).replace(/'/g, "\\'");
  const groupsJson = JSON.stringify(section.groups ?? []).replace(/'/g, "\\'");
  return `<?php
if ( ! defined( 'ABSPATH' ) ) exit;
if ( ! class_exists( 'WPB_Widget_Base' ) ) return;
class WPB_Widget_${safeId} extends WPB_Widget_Base {
    public function __construct( $data = array(), $args = null ) {
        $this->wpb_id = '${safeId}';
        $this->wpb_label = ${JSON.stringify(section.label)};
        $this->wpb_template_path = ${JSON.stringify(templateRelPath)};
        $this->wpb_fields = json_decode( '${fieldsJson}', true ) ?: array();
        $this->wpb_groups = json_decode( '${groupsJson}', true ) ?: array();
        parent::__construct( $data, $args );
    }
}
`;
}

const ASSET_EXT = new Set(["png", "jpg", "jpeg", "gif", "webp", "avif", "svg", "ico", "woff", "woff2", "ttf", "otf", "eot"]);

/**
 * Build a complete WordPress child theme ZIP. The ZIP lives under a single
 * top-level folder named `${projectSlug}` so it can be uploaded directly
 * via Appearance → Themes → Add New → Upload.
 */
export function generateThemeZip(input: ThemeInput): Buffer {
  const { projectSlug, projectName, combinedCss, combinedJs, pages, sourceZip } = input;
  const zip = new AdmZip();
  const root = projectSlug;

  zip.addFile(`${root}/style.css`, Buffer.from(STYLE_HEADER(projectName, projectSlug) + "\n" + combinedCss, "utf8"));
  zip.addFile(`${root}/index.php`, Buffer.from(INDEX_PHP, "utf8"));
  zip.addFile(`${root}/page.php`, Buffer.from(PAGE_PHP, "utf8"));
  zip.addFile(`${root}/header.php`, Buffer.from(HEADER_PHP, "utf8"));
  zip.addFile(`${root}/footer.php`, Buffer.from(FOOTER_PHP, "utf8"));
  zip.addFile(`${root}/inc/elementor-widgets.php`, Buffer.from(ELEMENTOR_WIDGETS_INC, "utf8"));
  zip.addFile(`${root}/assets/editor.js`, Buffer.from(EDITOR_JS(projectSlug), "utf8"));
  zip.addFile(`${root}/assets/template.css`, Buffer.from(combinedCss, "utf8"));
  if (combinedJs.trim().length > 0) {
    zip.addFile(`${root}/assets/template.js`, Buffer.from(combinedJs, "utf8"));
  }
  zip.addFile(`${root}/widgets/_base-widget.php`, Buffer.from(ELEMENTOR_BASE_WIDGET, "utf8"));

  const allBlockNames: string[] = [];
  const seen = new Set<string>();
  for (const page of pages) {
    for (const section of page.sections) {
      if (seen.has(section.blockName)) continue;
      seen.add(section.blockName);
      allBlockNames.push(section.blockName);
      const safeDir = section.blockName.split("/")[1];
      const blockRel = `blocks/${safeDir}`;
      zip.addFile(`${root}/${blockRel}/block.json`, Buffer.from(blockJsonFor(projectSlug, section), "utf8"));
      zip.addFile(`${root}/${blockRel}/render.php`, Buffer.from(blockRenderPhp(section, blockRel), "utf8"));
      zip.addFile(`${root}/${blockRel}/template.html`, Buffer.from(section.template, "utf8"));
      const widgetRelTpl = `${blockRel}/template.html`;
      zip.addFile(`${root}/widgets/widget-${safeDir}.php`, Buffer.from(widgetPhpFor(section, widgetRelTpl), "utf8"));
    }
  }

  zip.addFile(`${root}/functions.php`, Buffer.from(FUNCTIONS_PHP_TEMPLATE(projectSlug, allBlockNames), "utf8"));

  // Copy original images + fonts into assets/ so paths resolve identically.
  if (sourceZip) {
    try {
      const src = new AdmZip(sourceZip);
      for (const e of src.getEntries()) {
        if (e.isDirectory) continue;
        const name = e.entryName.replace(/\\/g, "/");
        if (name.startsWith("__MACOSX/") || name.includes("/.DS_Store")) continue;
        const ext = name.split(".").pop()?.toLowerCase() ?? "";
        if (!ASSET_EXT.has(ext)) continue;
        zip.addFile(`${root}/assets/${name}`, e.getData());
      }
    } catch {
      // Original ZIP missing or corrupt — skip the asset bundle (the theme
      // still renders, just with broken local image refs).
    }
  }

  const readme = `# ${projectName} (Pixel-Perfect Theme)

Generated by WP Bridge AI. Upload via WordPress → Appearance → Themes → Add New → Upload Theme. Activate.

Each section of the original site is registered as both a Gutenberg block and an Elementor widget. Edit content in either editor — the original CSS/JS keeps the design pixel-perfect.
`;
  zip.addFile(`${root}/README.md`, Buffer.from(readme, "utf8"));

  return zip.toBuffer();
}
