import AdmZip from "adm-zip";
import path from "node:path";
import type { ExtractedSection, ExtractedPage } from "./sectionFieldExtractor";

interface ThemeInput {
  projectName: string;
  projectSlug: string;       // theme dir name, lowercase-dashed
  combinedCss: string;
  combinedJs: string;
  pages: ExtractedPage[];
  sourceZip: Buffer | null;  // original ZIP — we copy images/fonts into the theme
}

const STYLE_HEADER = (name: string, slug: string) => `/*
Theme Name: ${name} (Pixel-Perfect)
Theme URI: https://wpbridgeai.com
Author: WP Bridge AI
Description: Auto-generated child theme for ${name}. Renders the original design pixel-for-pixel as native Elementor widgets.
Version: 1.0.0
Text Domain: ${slug}
*/
`;

const INDEX_PHP = `<?php
get_header();
if ( have_posts() ) :
  while ( have_posts() ) : the_post();
    the_content();
  endwhile;
endif;
get_footer();
`;

const HEADER_PHP = `<!doctype html>
<html <?php language_attributes(); ?>>
<head>
<meta charset="<?php bloginfo( 'charset' ); ?>">
<meta name="viewport" content="width=device-width, initial-scale=1">
<?php wp_head(); ?>
</head>
<body <?php body_class(); ?>>
`;

const FOOTER_PHP = `<?php wp_footer(); ?>
</body></html>
`;

// Dedicated page template — WordPress prefers page.php over index.php for
// pages, and Elementor's content rendering also expects this template to
// exist on a fully-fledged child theme.
const PAGE_PHP = `<?php
get_header();
while ( have_posts() ) : the_post();
    the_content();
endwhile;
get_footer();
`;

// Optional dedicated wiring file for Elementor widget registration. The
// main functions.php already has the same hook, but we also expose this
// file as the canonical place to override widget behaviour without editing
// functions.php itself.
const ELEMENTOR_WIDGETS_INC = `<?php
/**
 * Elementor widget wiring for the generated theme. This file is included
 * by functions.php after the base widget class is loaded. Custom widget
 * tweaks (icons, controls, categories) belong here.
 */
if ( ! defined( 'ABSPATH' ) ) exit;

add_action( 'elementor/elements/categories_registered', function ( $elements_manager ) {
    $elements_manager->add_category(
        'wpb-' . WPB_THEME_SLUG,
        array( 'title' => WPB_THEME_SLUG, 'icon' => 'fa fa-puzzle-piece' )
    );
} );
`;

const FUNCTIONS_PHP_TEMPLATE = (slug: string, blockNames: string[]) => `<?php
/**
 * ${slug} — generated by WP Bridge AI.
 * Enqueues the original template's CSS/JS and registers per-section
 * Elementor widgets. There is no Gutenberg block path: every editable
 * surface lives inside the matching Elementor widget.
 */
if ( ! defined( 'ABSPATH' ) ) exit;

define( 'WPB_THEME_SLUG', '${slug}' );
define( 'WPB_THEME_DIR', get_stylesheet_directory() );
define( 'WPB_THEME_URI', get_stylesheet_directory_uri() );

add_action( 'wp_enqueue_scripts', function () {
    wp_enqueue_style( 'wpb-theme-style', WPB_THEME_URI . '/style.css', array(), '1.0.0' );
    wp_enqueue_style( 'wpb-template-css', WPB_THEME_URI . '/assets/template.css', array(), '1.0.0' );
    if ( file_exists( WPB_THEME_DIR . '/assets/template.js' ) ) {
        wp_enqueue_script( 'wpb-template-js', WPB_THEME_URI . '/assets/template.js', array( 'jquery' ), '1.0.0', true );
    }
}, 100 );

/**
 * Render helper shared by every Elementor widget. Loads the section
 * template, performs typed placeholder substitution
 * ({{TEXT:k}}, {{URL:k}}, {{ATTR:k}}, {{TAG:k}}, {{LIST:k}}), and
 * returns the resulting HTML.
 */
function wpb_render_section_template( string $template_path, array $attrs ): string {
    if ( ! file_exists( $template_path ) ) return '';
    $tpl = file_get_contents( $template_path );
    // First pass: rebase any {{THEME_URI}} placeholders to the actual child theme URL.
    // Field defaults that came from the original HTML's relative asset paths (images,
    // CSS backgrounds, etc.) also use this placeholder so they keep working when the
    // user edits and re-saves them.
    $theme_uri = esc_url( get_stylesheet_directory_uri() );
    $tpl = str_replace( '{{THEME_URI}}', $theme_uri, $tpl );
    foreach ( $attrs as $k => $v ) {
        if ( is_string( $v ) && strpos( $v, '{{THEME_URI}}' ) !== false ) {
            $attrs[ $k ] = str_replace( '{{THEME_URI}}', $theme_uri, $v );
        }
    }
    $rendered = preg_replace_callback(
        '/\\{\\{(TEXT|ATTR|URL|TAG|LIST):([A-Za-z0-9_]+)\\}\\}/',
        function ( $m ) use ( $attrs ) {
            $val = $attrs[ $m[2] ] ?? '';
            if ( ! is_string( $val ) ) $val = (string) $val;
            switch ( $m[1] ) {
                case 'TEXT': return esc_html( $val );
                case 'ATTR': return esc_attr( $val );
                case 'URL':  return esc_url( $val );
                case 'TAG':  return preg_match( '/^h[1-6]$/', $val ) ? $val : 'h2';
                case 'LIST': {
                    // List items come in as one-per-line (the textarea
                    // control surfaces the items in the Elementor sidebar).
                    // Empty lines are dropped so trailing newlines don't
                    // produce empty <li>s in the rendered output.
                    $items = preg_split( '/\\r?\\n/', $val );
                    $out = '';
                    foreach ( $items as $item ) {
                        $item = trim( $item );
                        if ( $item === '' ) continue;
                        $out .= '<li>' . esc_html( $item ) . '</li>';
                    }
                    return $out;
                }
            }
            return '';
        },
        $tpl
    ) ?? '';
    // Image srcset pass: <img data-wpb-media="key"> gets swapped out for
    // wp_get_attachment_image() output (which carries proper srcset/sizes
    // attributes) whenever the saved MEDIA control carries a non-zero
    // attachment id. When no id is available we leave the <img> alone —
    // its src has already been substituted by the URL pass — and just
    // strip the marker.
    $rendered = preg_replace_callback(
        '/<img\\b([^>]*?)\\sdata-wpb-media="([A-Za-z0-9_]+)"([^>]*?)\\/?>(?!\\s*<\\/img>)/i',
        function ( $m ) use ( $attrs ) {
            $key = $m[2];
            $id  = isset( $attrs[ '__media_id:' . $key ] ) ? (int) $attrs[ '__media_id:' . $key ] : 0;
            $rest = $m[1] . $m[3];
            $rest = trim( preg_replace( '/\\sdata-wpb-media="[^"]*"/', '', ' ' . $rest ) );
            if ( $id > 0 && function_exists( 'wp_get_attachment_image' ) ) {
                // Preserve any class / alt / id attributes the original
                // template carried so the swapped image keeps its
                // styling hooks. wp_get_attachment_image() will append
                // its own srcset/sizes attributes on top.
                $extra = array();
                if ( preg_match( '/\\sclass="([^"]*)"/i', $rest, $cm ) ) $extra['class'] = $cm[1];
                if ( preg_match( '/\\salt="([^"]*)"/i',   $rest, $am ) ) $extra['alt']   = $am[1];
                if ( preg_match( '/\\sid="([^"]*)"/i',    $rest, $im ) ) $extra['id']    = $im[1];
                $img_html = wp_get_attachment_image( $id, 'full', false, $extra );
                if ( $img_html ) return $img_html;
            }
            $self_close = substr( $m[0], -2, 1 ) === '/' ? ' />' : '>';
            return '<img ' . $rest . $self_close;
        },
        $rendered
    ) ?? $rendered;
    // Button-link wrap pass: every <button data-wpb-button-link="key">
    // gets wrapped with an <a> when the saved URL control carries a
    // non-empty value. The same rel/target metadata that powers the
    // <a data-wpb-link> pass is reused. The marker is always stripped.
    $rendered = preg_replace_callback(
        '/<button\\b([^>]*?)\\sdata-wpb-button-link="([A-Za-z0-9_]+)"([^>]*)>(.*?)<\\/button>/is',
        function ( $m ) use ( $attrs ) {
            $key   = $m[2];
            $href  = isset( $attrs[ $key ] )            ? (string) $attrs[ $key ]            : '';
            $rel   = isset( $attrs[ '__rel:' . $key ] ) ? (string) $attrs[ '__rel:' . $key ] : '';
            $target = isset( $attrs[ '__target:' . $key ] ) ? (string) $attrs[ '__target:' . $key ] : '';
            $rest = $m[1] . $m[3];
            $rest = trim( preg_replace( '/\\sdata-wpb-button-link="[^"]*"/', '', ' ' . $rest ) );
            $btn = '<button ' . $rest . '>' . $m[4] . '</button>';
            if ( $href === '' ) return $btn;
            $extra = '';
            if ( $rel !== '' )    $extra .= ' rel="'    . esc_attr( $rel )    . '"';
            if ( $target !== '' ) $extra .= ' target="' . esc_attr( $target ) . '"';
            return '<a href="' . esc_url( $href ) . '"' . $extra . '>' . $btn . '</a>';
        },
        $rendered
    ) ?? $rendered;
    // Link rel/target pass: every <a data-wpb-link="key"> gets its rel
    // and target attributes rewritten from the URL control's metadata
    // (nofollow flag → rel="nofollow", is_external flag → target="_blank"
    //  + rel="noopener noreferrer"). Drops the data-wpb-link marker on
    // its way out so it doesn't leak into the rendered page.
    $rendered = preg_replace_callback(
        '/<a\\b([^>]*?)\\sdata-wpb-link="([A-Za-z0-9_]+)"([^>]*)>/i',
        function ( $m ) use ( $attrs ) {
            $key   = $m[2];
            $rel   = isset( $attrs[ '__rel:' . $key ] )    ? (string) $attrs[ '__rel:' . $key ]    : '';
            $target = isset( $attrs[ '__target:' . $key ] ) ? (string) $attrs[ '__target:' . $key ] : '';
            $rest = $m[1] . $m[3];
            // Drop any pre-existing rel / target so we always reflect
            // the saved control values rather than the original markup.
            $rest = preg_replace( '/\\s(?:rel|target)="[^"]*"/i', '', $rest );
            $rest = trim( $rest );
            $extra = '';
            if ( $rel !== '' )    $extra .= ' rel="'    . esc_attr( $rel )    . '"';
            if ( $target !== '' ) $extra .= ' target="' . esc_attr( $target ) . '"';
            return '<a ' . $rest . $extra . '>';
        },
        $rendered
    ) ?? $rendered;
    // Icon swap pass: any <i data-wpb-icon="key"> or <span data-wpb-icon="key">
    // gets the marker stripped on its way out. When the saved ICONS
    // control points at an SVG upload (library === 'svg'), the element
    // is replaced wholesale with an <img src="..."> so the uploaded
    // glyph actually renders in the browser. Font-icon edits are
    // already taken care of by the {{ATTR:k}} substitution that
    // rewrites the element's class attribute.
    $rendered = preg_replace_callback(
        '/<(i|span)\\b([^>]*?)\\sdata-wpb-icon="([A-Za-z0-9_]+)"([^>]*?)>(.*?)<\\/\\1>/is',
        function ( $m ) use ( $attrs ) {
            $tagn = strtolower( $m[1] );
            $key  = $m[3];
            $svg  = isset( $attrs[ '__icon_svg:' . $key ] ) ? (string) $attrs[ '__icon_svg:' . $key ] : '';
            $rest = $m[2] . $m[4];
            $rest = preg_replace( '/\\sdata-wpb-icon="[^"]*"/', '', ' ' . $rest );
            $rest = trim( $rest );
            if ( $svg !== '' ) {
                // Preserve the original class hook so any sibling CSS
                // (sizing, color, alignment) keeps applying to the swapped
                // SVG. Drop the (now-empty) class="" emitted by the
                // {{ATTR:k}} pass — a stray empty class attribute looks
                // sloppy in the rendered HTML.
                $cls = '';
                if ( preg_match( '/\\sclass="([^"]*)"/i', ' ' . $rest, $cm ) ) $cls = trim( $cm[1] );
                $cls_attr = $cls === '' ? '' : ' class="' . esc_attr( $cls ) . '"';
                return '<img src="' . esc_url( $svg ) . '" alt=""' . $cls_attr . ' />';
            }
            $open_attrs = $rest === '' ? '' : ' ' . $rest;
            return '<' . $tagn . $open_attrs . '>' . $m[5] . '</' . $tagn . '>';
        },
        $rendered
    ) ?? $rendered;
    // Heading tag-swap pass: any element marked with data-wpb-tag="key"
    // gets its open/close tag rewritten to whichever h1-h6 the saved field
    // value asks for. We only touch h1-h6 elements so other markup stays
    // intact, and we sanitise the target tag against the same allowlist.
    $rendered = preg_replace_callback(
        '/<(h[1-6])([^>]*?)\\sdata-wpb-tag="([A-Za-z0-9_]+)"([^>]*)>(.*?)<\\/\\1>/is',
        function ( $m ) use ( $attrs ) {
            $orig = $m[1];
            $key  = $m[3];
            $next = isset( $attrs[ $key ] ) && is_string( $attrs[ $key ] ) ? $attrs[ $key ] : $orig;
            if ( ! preg_match( '/^h[1-6]$/', $next ) ) $next = $orig;
            $rest_attrs = trim( $m[2] . ' ' . $m[4] );
            $rest_attrs = preg_replace( '/\\sdata-wpb-tag="[^"]*"/', '', ' ' . $rest_attrs );
            $rest_attrs = trim( $rest_attrs );
            $open_attrs = $rest_attrs === '' ? '' : ' ' . $rest_attrs;
            return '<' . $next . $open_attrs . '>' . $m[5] . '</' . $next . '>';
        },
        $rendered
    ) ?? $rendered;
    return $rendered;
}

/**
 * Register Elementor widgets when Elementor is active. Every editable
 * surface in the migrated site lives inside one of these widgets — there
 * is no Gutenberg block path.
 */
// Optional Elementor wiring overrides — registers a category etc.
if ( file_exists( WPB_THEME_DIR . '/inc/elementor-widgets.php' ) ) {
    require_once WPB_THEME_DIR . '/inc/elementor-widgets.php';
}

add_action( 'elementor/widgets/register', function ( $widgets_manager ) {
    $widgets_dir = WPB_THEME_DIR . '/widgets';
    if ( ! is_dir( $widgets_dir ) ) return;
    require_once WPB_THEME_DIR . '/widgets/_base-widget.php';
    foreach ( glob( $widgets_dir . '/widget-*.php' ) as $widget_file ) {
        require_once $widget_file;
        // Generated widget files are named widget-<safeDir>.php and the class
        // inside is WPB_Widget_<safeDir-with-dashes-replaced-by-underscores>.
        // Strip the 'widget-' prefix FIRST, then normalise.
        $base  = preg_replace( '/^widget-/', '', basename( $widget_file, '.php' ) );
        $class = 'WPB_Widget_' . preg_replace( '/[^a-zA-Z0-9_]/', '_', $base );
        if ( class_exists( $class ) ) {
            $widgets_manager->register( new $class() );
        }
    }
} );
`;

const ELEMENTOR_BASE_WIDGET = `<?php
if ( ! defined( 'ABSPATH' ) ) exit;
if ( ! class_exists( 'WPB_Widget_Base' ) && class_exists( '\\\\Elementor\\\\Widget_Base' ) ) {
class WPB_Widget_Base extends \\Elementor\\Widget_Base {
    protected $wpb_id = '';
    protected $wpb_label = '';
    protected $wpb_template_path = '';
    protected $wpb_fields = array();
    protected $wpb_groups = array();

    public function get_name() { return 'wpb_' . $this->wpb_id; }
    public function get_title() { return $this->wpb_label; }
    public function get_icon() { return 'eicon-section'; }
    public function get_categories() { return array( 'general' ); }

    /**
     * Map our control type tag to Elementor's Controls_Manager constant.
     * Heading tag pickers use the native CHOOSE control (the same one
     * Elementor's own Heading widget exposes), and lists use REPEATER
     * so each item is editable as its own row.
     */
    private function wpb_control_type( $type ) {
        switch ( $type ) {
            case 'textarea': return \\Elementor\\Controls_Manager::TEXTAREA;
            case 'url':      return \\Elementor\\Controls_Manager::URL;
            case 'media':    return \\Elementor\\Controls_Manager::MEDIA;
            case 'choose':   return \\Elementor\\Controls_Manager::CHOOSE;
            case 'repeater': return \\Elementor\\Controls_Manager::REPEATER;
            case 'icons':    return \\Elementor\\Controls_Manager::ICONS;
            case 'text':
            default:         return \\Elementor\\Controls_Manager::TEXT;
        }
    }

    /**
     * Build the icon-toggle option set for a CHOOSE control. For heading
     * tag pickers we surface every allowed value (h1..h6) with a short
     * label; an eicon is used when one is available so the UI matches
     * the native Elementor Heading widget.
     */
    private function wpb_choose_options( $opts ) {
        $out = array();
        foreach ( $opts as $opt ) {
            $key = (string) $opt;
            $out[ $key ] = array(
                'title' => strtoupper( $key ),
                'icon'  => 'eicon-editor-' . $key,
            );
        }
        return $out;
    }

    protected function register_controls() {
        // Preferred path: walk the semantic groups[] and emit one
        // start_controls_section per element (Button, Image, Heading...).
        // Falls back to the old flat fields[] list when groups are empty
        // (legacy theme upgrade path).
        if ( is_array( $this->wpb_groups ) && count( $this->wpb_groups ) > 0 ) {
            foreach ( $this->wpb_groups as $g ) {
                $section_id = 'wpb_grp_' . preg_replace( '/[^a-zA-Z0-9_]/', '_', $g['id'] ?? 'g' );
                $this->start_controls_section( $section_id, array(
                    'label' => esc_html( $g['label'] ?? 'Section' ),
                    'tab'   => \\Elementor\\Controls_Manager::TAB_CONTENT,
                ) );
                foreach ( ($g['controls'] ?? array()) as $c ) {
                    $type = $this->wpb_control_type( $c['type'] ?? 'text' );
                    $args = array(
                        'label'       => esc_html( $c['label'] ?? $c['key'] ),
                        'type'        => $type,
                        'label_block' => true,
                    );
                    if ( $type === \\Elementor\\Controls_Manager::URL ) {
                        $args['default'] = array(
                            'url'         => $c['default'] ?? '',
                            'is_external' => false,
                            'nofollow'    => false,
                        );
                    } elseif ( $type === \\Elementor\\Controls_Manager::MEDIA ) {
                        $args['default'] = array(
                            'url' => $c['default'] ?? '',
                        );
                    } elseif ( $type === \\Elementor\\Controls_Manager::ICONS ) {
                        // ICONS control: default value carries the
                        // original icon-font class string and we tag it
                        // as a Font Awesome library entry. Customers can
                        // also swap to an SVG upload via the attached
                        // MEDIA picker — that case is handled by the
                        // wpb_settings_to_attrs reduction at render time.
                        $args['default'] = array(
                            'value'   => $c['default'] ?? '',
                            'library' => 'fa-solid',
                        );
                    } elseif ( $type === \\Elementor\\Controls_Manager::CHOOSE ) {
                        $opts = isset( $c['options'] ) && is_array( $c['options'] ) ? $c['options'] : array();
                        $args['options']     = $this->wpb_choose_options( $opts );
                        $args['default']     = $c['default'] ?? ( $opts[0] ?? '' );
                        $args['toggle']      = false;
                    } elseif ( $type === \\Elementor\\Controls_Manager::REPEATER ) {
                        // Build a single-field repeater: each row carries an
                        // "item" TEXT field that maps back to one <li>.
                        // Defaults are seeded from the textarea-style
                        // newline-joined string the extractor stored.
                        $repeater = new \\Elementor\\Repeater();
                        $repeater->add_control( 'item', array(
                            'label'       => esc_html__( 'Item', 'wpb' ),
                            'type'        => \\Elementor\\Controls_Manager::TEXT,
                            'default'     => '',
                            'label_block' => true,
                        ) );
                        $args['fields']  = $repeater->get_controls();
                        $args['default'] = array();
                        $seed = is_string( $c['default'] ?? '' ) ? (string) $c['default'] : '';
                        if ( $seed !== '' ) {
                            foreach ( preg_split( '/\\r?\\n/', $seed ) as $row ) {
                                $row = trim( $row );
                                if ( $row === '' ) continue;
                                $args['default'][] = array( 'item' => $row );
                            }
                        }
                        $args['title_field'] = '{{{ item }}}';
                    } else {
                        $args['default'] = $c['default'] ?? '';
                    }
                    $this->add_control( $c['key'], $args );
                }
                $this->end_controls_section();
            }
            return;
        }

        $this->start_controls_section( 'content', array(
            'label' => esc_html__( 'Content', 'wpb' ),
            'tab'   => \\Elementor\\Controls_Manager::TAB_CONTENT,
        ) );
        foreach ( $this->wpb_fields as $f ) {
            $type = $f['type'] === 'text' && strlen( $f['default'] ?? '' ) > 80
                ? \\Elementor\\Controls_Manager::TEXTAREA
                : \\Elementor\\Controls_Manager::TEXT;
            $this->add_control( $f['key'], array(
                'label'   => esc_html( $f['label'] ?? $f['key'] ),
                'type'    => $type,
                'default' => $f['default'] ?? '',
            ) );
        }
        $this->end_controls_section();
    }

    /**
     * Reduce the Elementor settings array (which uses structured shapes
     * for URL / MEDIA controls) down to the flat scalar map the template
     * renderer expects. Each control's value lands at $attrs[$fieldKey],
     * keyed by whatever placeholder ({{TEXT:k}}, {{URL:k}}, ...) the
     * template uses.
     */
    private function wpb_settings_to_attrs( $settings ) {
        $attrs = array();
        if ( ! is_array( $this->wpb_groups ) ) return $settings;
        foreach ( $this->wpb_groups as $g ) {
            foreach ( ($g['controls'] ?? array()) as $c ) {
                $ck  = $c['key'] ?? '';
                $fk  = $c['fieldKey'] ?? $ck;
                $val = $settings[ $ck ] ?? ( $c['default'] ?? '' );
                $type = $c['type'] ?? 'text';
                if ( $type === 'url' && is_array( $val ) ) {
                    // Capture the URL control's rel/target metadata so the
                    // post-render pass can stamp them back onto any
                    // <a data-wpb-link="<key>"> element. Two synthetic
                    // attrs keys are used so they can never collide with
                    // a real placeholder name (placeholders are matched
                    // against [A-Za-z0-9_]+ only).
                    $is_external = ! empty( $val['is_external'] );
                    $nofollow    = ! empty( $val['nofollow'] );
                    $rel_parts = array();
                    if ( $nofollow )    $rel_parts[] = 'nofollow';
                    if ( $is_external ) { $rel_parts[] = 'noopener'; $rel_parts[] = 'noreferrer'; }
                    $attrs[ '__rel:'    . $ck ] = implode( ' ', array_unique( $rel_parts ) );
                    $attrs[ '__target:' . $ck ] = $is_external ? '_blank' : '';
                    $val = isset( $val['url'] ) ? (string) $val['url'] : '';
                } elseif ( $type === 'icons' && is_array( $val ) ) {
                    // ICONS control: shape is { value, library }. For
                    // font icons (library != 'svg'), value is the class
                    // string and we surface it as the icon's class via
                    // the {{ATTR:k}} substitution. For SVG uploads, the
                    // value is itself { id, url } — we stash the URL on
                    // a synthetic attrs key (__icon_svg:<key>) so the
                    // post-render pass can swap the <i>/<span> for an
                    // <img src="..."> with the uploaded SVG.
                    $library = isset( $val['library'] ) ? (string) $val['library'] : '';
                    $iv      = $val['value'] ?? '';
                    if ( $library === 'svg' && is_array( $iv ) ) {
                        $svg_url = isset( $iv['url'] ) ? (string) $iv['url'] : '';
                        $attrs[ '__icon_svg:' . $ck ] = $svg_url;
                        $val = '';
                    } else {
                        $val = is_string( $iv ) ? $iv : (string) $iv;
                    }
                } elseif ( $type === 'media' && is_array( $val ) ) {
                    // Capture the attachment id alongside the URL so the
                    // post-render image pass can swap a plain <img> for
                    // wp_get_attachment_image() (which emits proper
                    // srcset/sizes) when the user picks an image from
                    // the WordPress media library.
                    $attrs[ '__media_id:' . $ck ] = isset( $val['id'] ) ? (int) $val['id'] : 0;
                    $val = isset( $val['url'] ) ? (string) $val['url'] : '';
                } elseif ( $type === 'repeater' && is_array( $val ) ) {
                    // Collapse the repeater rows back into the
                    // newline-joined text the {{LIST:k}} renderer
                    // expects. Each row is either an associative
                    // array with an "item" field or, defensively, a
                    // bare scalar.
                    $rows = array();
                    foreach ( $val as $row ) {
                        if ( is_array( $row ) ) {
                            $item = isset( $row['item'] ) ? (string) $row['item'] : '';
                        } else {
                            $item = (string) $row;
                        }
                        $item = trim( $item );
                        if ( $item !== '' ) $rows[] = $item;
                    }
                    $val = implode( "\\n", $rows );
                } else {
                    $val = is_string( $val ) ? $val : (string) $val;
                }
                $attrs[ $fk ] = $val;
            }
        }
        return $attrs;
    }

    protected function render() {
        $settings = $this->get_settings_for_display();
        $attrs    = is_array( $this->wpb_groups ) && count( $this->wpb_groups ) > 0
            ? $this->wpb_settings_to_attrs( $settings )
            : $settings;
        echo wpb_render_section_template( WPB_THEME_DIR . '/' . $this->wpb_template_path, $attrs );
    }
}
}
`;

function widgetPhpFor(section: ExtractedSection, templateRelPath: string): string {
  const safeId = section.blockName.split("/")[1].replace(/[^a-zA-Z0-9_]/g, "_");
  const fieldsJson = JSON.stringify(section.fields).replace(/'/g, "\\'");
  const groupsJson = JSON.stringify(section.groups ?? []).replace(/'/g, "\\'");
  return `<?php
if ( ! defined( 'ABSPATH' ) ) exit;
if ( ! class_exists( 'WPB_Widget_Base' ) ) return;
class WPB_Widget_${safeId} extends WPB_Widget_Base {
    public function __construct( $data = array(), $args = null ) {
        $this->wpb_id = '${safeId}';
        $this->wpb_label = ${JSON.stringify(section.label)};
        $this->wpb_template_path = ${JSON.stringify(templateRelPath)};
        $this->wpb_fields = json_decode( '${fieldsJson}', true ) ?: array();
        $this->wpb_groups = json_decode( '${groupsJson}', true ) ?: array();
        parent::__construct( $data, $args );
    }
}
`;
}

const ASSET_EXT = new Set(["png", "jpg", "jpeg", "gif", "webp", "avif", "svg", "ico", "woff", "woff2", "ttf", "otf", "eot"]);

/**
 * Build a complete WordPress child theme ZIP. The ZIP lives under a single
 * top-level folder named `${projectSlug}` so it can be uploaded directly
 * via Appearance → Themes → Add New → Upload.
 */
export function generateThemeZip(input: ThemeInput): Buffer {
  const { projectSlug, projectName, combinedCss, combinedJs, pages, sourceZip } = input;
  const zip = new AdmZip();
  const root = projectSlug;

  zip.addFile(`${root}/style.css`, Buffer.from(STYLE_HEADER(projectName, projectSlug) + "\n" + combinedCss, "utf8"));
  zip.addFile(`${root}/index.php`, Buffer.from(INDEX_PHP, "utf8"));
  zip.addFile(`${root}/page.php`, Buffer.from(PAGE_PHP, "utf8"));
  zip.addFile(`${root}/header.php`, Buffer.from(HEADER_PHP, "utf8"));
  zip.addFile(`${root}/footer.php`, Buffer.from(FOOTER_PHP, "utf8"));
  zip.addFile(`${root}/inc/elementor-widgets.php`, Buffer.from(ELEMENTOR_WIDGETS_INC, "utf8"));
  zip.addFile(`${root}/assets/template.css`, Buffer.from(combinedCss, "utf8"));
  if (combinedJs.trim().length > 0) {
    zip.addFile(`${root}/assets/template.js`, Buffer.from(combinedJs, "utf8"));
  }
  zip.addFile(`${root}/widgets/_base-widget.php`, Buffer.from(ELEMENTOR_BASE_WIDGET, "utf8"));

  const allBlockNames: string[] = [];
  const seen = new Set<string>();
  for (const page of pages) {
    for (const section of page.sections) {
      if (seen.has(section.blockName)) continue;
      seen.add(section.blockName);
      // Sections that ship as a native Elementor `section → column → widget`
      // tree don't need a PHP widget class — Elementor's built-in widgets
      // (heading / image / button / icon / icon-list / text-editor / html)
      // render them directly. Skip the per-section PHP file and template.
      if (section.nativeElementor) continue;
      allBlockNames.push(section.blockName);
      const safeDir = section.blockName.split("/")[1];
      // Templates live under widgets/templates/<safeDir>/template.html so the
      // theme has no Gutenberg block infrastructure (no blocks/ dir, no
      // block.json, no editor.js). The Elementor widget loads the template
      // via wpb_render_section_template().
      const tplRel = `widgets/templates/${safeDir}/template.html`;
      zip.addFile(`${root}/${tplRel}`, Buffer.from(section.template, "utf8"));
      zip.addFile(`${root}/widgets/widget-${safeDir}.php`, Buffer.from(widgetPhpFor(section, tplRel), "utf8"));
    }
  }

  zip.addFile(`${root}/functions.php`, Buffer.from(FUNCTIONS_PHP_TEMPLATE(projectSlug, allBlockNames), "utf8"));

  // Copy original images + fonts into assets/ so paths resolve identically.
  if (sourceZip) {
    try {
      const src = new AdmZip(sourceZip);
      for (const e of src.getEntries()) {
        if (e.isDirectory) continue;
        const name = e.entryName.replace(/\\/g, "/");
        if (name.startsWith("__MACOSX/") || name.includes("/.DS_Store")) continue;
        const ext = name.split(".").pop()?.toLowerCase() ?? "";
        if (!ASSET_EXT.has(ext)) continue;
        zip.addFile(`${root}/assets/${name}`, e.getData());
      }
    } catch {
      // Original ZIP missing or corrupt — skip the asset bundle (the theme
      // still renders, just with broken local image refs).
    }
  }

  const readme = `# ${projectName} (Pixel-Perfect Theme)

Generated by WP Bridge AI. Upload via WordPress → Appearance → Themes → Add New → Upload Theme. Activate.

Each section of the original site is registered as a native Elementor widget with semantic controls (button, link, image, heading, text, list). Edit content inside Elementor — the original CSS/JS keeps the design pixel-perfect.
`;
  zip.addFile(`${root}/README.md`, Buffer.from(readme, "utf8"));

  return zip.toBuffer();
}
