import AdmZip from "adm-zip";
import path from "node:path";
import type { ExtractedSection, ExtractedPage } from "./sectionFieldExtractor";

interface ThemeInput {
  projectName: string;
  projectSlug: string;       // theme dir name, lowercase-dashed
  combinedCss: string;
  combinedJs: string;
  pages: ExtractedPage[];
  sourceZip: Buffer | null;  // original ZIP — we copy images/fonts into the theme
  /**
   * Project conversion mode. When set to `"legacy_native"`, the
   * generated PHP widgets register a native-flavoured Elementor sidebar
   * (Group_Control_Typography + Text Color + Border + ... per group,
   * scoped to each leaf's `wpb-leaf-{gid}` CSS class) instead of the
   * generic flat control list. The render path is unchanged, so visual
   * fidelity matches plain `legacy` mode. Other values (or omission)
   * fall back to the generic legacy controls.
   */
  conversionMode?: string;
}

const STYLE_HEADER = (name: string, slug: string) => `/*
Theme Name: ${name} (Pixel-Perfect)
Theme URI: https://wpbridgeai.com
Author: WP Bridge AI
Description: Auto-generated child theme for ${name}. Renders the original design pixel-for-pixel as native Elementor widgets.
Version: 1.0.0
Text Domain: ${slug}
*/
`;

const INDEX_PHP = `<?php
get_header();
if ( have_posts() ) :
  while ( have_posts() ) : the_post();
    the_content();
  endwhile;
endif;
get_footer();
`;

const HEADER_PHP = `<!doctype html>
<html <?php language_attributes(); ?>>
<head>
<meta charset="<?php bloginfo( 'charset' ); ?>">
<meta name="viewport" content="width=device-width, initial-scale=1">
<?php wp_head(); ?>
</head>
<body <?php body_class(); ?>>
`;

const FOOTER_PHP = `<?php wp_footer(); ?>
</body></html>
`;

// Dedicated page template — WordPress prefers page.php over index.php for
// pages, and Elementor's content rendering also expects this template to
// exist on a fully-fledged child theme.
const PAGE_PHP = `<?php
get_header();
while ( have_posts() ) : the_post();
    the_content();
endwhile;
get_footer();
`;

// Optional dedicated wiring file for Elementor widget registration. The
// main functions.php already has the same hook, but we also expose this
// file as the canonical place to override widget behaviour without editing
// functions.php itself.
const ELEMENTOR_WIDGETS_INC = `<?php
/**
 * Elementor widget wiring for the generated theme. This file is included
 * by functions.php after the base widget class is loaded. Custom widget
 * tweaks (icons, controls, categories) belong here.
 */
if ( ! defined( 'ABSPATH' ) ) exit;

add_action( 'elementor/elements/categories_registered', function ( $elements_manager ) {
    $elements_manager->add_category(
        'wpb-' . WPB_THEME_SLUG,
        array( 'title' => WPB_THEME_SLUG, 'icon' => 'fa fa-puzzle-piece' )
    );
} );
`;

const FUNCTIONS_PHP_TEMPLATE = (slug: string, blockNames: string[]) => `<?php
/**
 * ${slug} — generated by WP Bridge AI.
 * Enqueues the original template's CSS/JS and registers per-section
 * Elementor widgets. There is no Gutenberg block path: every editable
 * surface lives inside the matching Elementor widget.
 */
if ( ! defined( 'ABSPATH' ) ) exit;

define( 'WPB_THEME_SLUG', '${slug}' );
define( 'WPB_THEME_DIR', get_stylesheet_directory() );
define( 'WPB_THEME_URI', get_stylesheet_directory_uri() );

add_action( 'wp_enqueue_scripts', function () {
    wp_enqueue_style( 'wpb-theme-style', WPB_THEME_URI . '/style.css', array(), '1.0.0' );
    wp_enqueue_style( 'wpb-template-css', WPB_THEME_URI . '/assets/template.css', array(), '1.0.0' );
    if ( file_exists( WPB_THEME_DIR . '/assets/template.js' ) ) {
        wp_enqueue_script( 'wpb-template-js', WPB_THEME_URI . '/assets/template.js', array( 'jquery' ), '1.0.0', true );
    }
}, 100 );

/**
 * Render helper shared by every Elementor widget. Loads the section
 * template, performs typed placeholder substitution
 * ({{TEXT:k}}, {{URL:k}}, {{ATTR:k}}, {{TAG:k}}, {{LIST:k}}), and
 * returns the resulting HTML.
 */
function wpb_render_section_template( string $template_path, array $attrs ): string {
    if ( ! file_exists( $template_path ) ) return '';
    $tpl = file_get_contents( $template_path );
    // First pass: rebase any {{THEME_URI}} placeholders to the actual child theme URL.
    // Field defaults that came from the original HTML's relative asset paths (images,
    // CSS backgrounds, etc.) also use this placeholder so they keep working when the
    // user edits and re-saves them.
    $theme_uri = esc_url( get_stylesheet_directory_uri() );
    $tpl = str_replace( '{{THEME_URI}}', $theme_uri, $tpl );
    foreach ( $attrs as $k => $v ) {
        if ( is_string( $v ) && strpos( $v, '{{THEME_URI}}' ) !== false ) {
            $attrs[ $k ] = str_replace( '{{THEME_URI}}', $theme_uri, $v );
        }
    }
    $rendered = preg_replace_callback(
        '/\\{\\{(TEXT|ATTR|URL|TAG|LIST):([A-Za-z0-9_]+)\\}\\}/',
        function ( $m ) use ( $attrs ) {
            $val = $attrs[ $m[2] ] ?? '';
            if ( ! is_string( $val ) ) $val = (string) $val;
            switch ( $m[1] ) {
                case 'TEXT': return esc_html( $val );
                case 'ATTR': return esc_attr( $val );
                case 'URL':  return esc_url( $val );
                case 'TAG':  return preg_match( '/^h[1-6]$/', $val ) ? $val : 'h2';
                case 'LIST': {
                    // List items come in as one-per-line (the textarea
                    // control surfaces the items in the Elementor sidebar).
                    // Empty lines are dropped so trailing newlines don't
                    // produce empty <li>s in the rendered output.
                    $items = preg_split( '/\\r?\\n/', $val );
                    $out = '';
                    foreach ( $items as $item ) {
                        $item = trim( $item );
                        if ( $item === '' ) continue;
                        $out .= '<li>' . esc_html( $item ) . '</li>';
                    }
                    return $out;
                }
            }
            return '';
        },
        $tpl
    ) ?? '';
    // Image srcset pass: <img data-wpb-media="key"> gets swapped out for
    // wp_get_attachment_image() output (which carries proper srcset/sizes
    // attributes) whenever the saved MEDIA control carries a non-zero
    // attachment id. When no id is available we leave the <img> alone —
    // its src has already been substituted by the URL pass — and just
    // strip the marker.
    $rendered = preg_replace_callback(
        '/<img\\b([^>]*?)\\sdata-wpb-media="([A-Za-z0-9_]+)"([^>]*?)\\/?>(?!\\s*<\\/img>)/i',
        function ( $m ) use ( $attrs ) {
            $key = $m[2];
            $id  = isset( $attrs[ '__media_id:' . $key ] ) ? (int) $attrs[ '__media_id:' . $key ] : 0;
            $rest = $m[1] . $m[3];
            $rest = trim( preg_replace( '/\\sdata-wpb-media="[^"]*"/', '', ' ' . $rest ) );
            if ( $id > 0 && function_exists( 'wp_get_attachment_image' ) ) {
                // Preserve any class / alt / id attributes the original
                // template carried so the swapped image keeps its
                // styling hooks. wp_get_attachment_image() will append
                // its own srcset/sizes attributes on top.
                $extra = array();
                if ( preg_match( '/\\sclass="([^"]*)"/i', $rest, $cm ) ) $extra['class'] = $cm[1];
                if ( preg_match( '/\\salt="([^"]*)"/i',   $rest, $am ) ) $extra['alt']   = $am[1];
                if ( preg_match( '/\\sid="([^"]*)"/i',    $rest, $im ) ) $extra['id']    = $im[1];
                $img_html = wp_get_attachment_image( $id, 'full', false, $extra );
                if ( $img_html ) return $img_html;
            }
            $self_close = substr( $m[0], -2, 1 ) === '/' ? ' />' : '>';
            return '<img ' . $rest . $self_close;
        },
        $rendered
    ) ?? $rendered;
    // Button-link wrap pass: every <button data-wpb-button-link="key">
    // gets wrapped with an <a> when the saved URL control carries a
    // non-empty value. The same rel/target metadata that powers the
    // <a data-wpb-link> pass is reused. The marker is always stripped.
    $rendered = preg_replace_callback(
        '/<button\\b([^>]*?)\\sdata-wpb-button-link="([A-Za-z0-9_]+)"([^>]*)>(.*?)<\\/button>/is',
        function ( $m ) use ( $attrs ) {
            $key   = $m[2];
            $href  = isset( $attrs[ $key ] )            ? (string) $attrs[ $key ]            : '';
            $rel   = isset( $attrs[ '__rel:' . $key ] ) ? (string) $attrs[ '__rel:' . $key ] : '';
            $target = isset( $attrs[ '__target:' . $key ] ) ? (string) $attrs[ '__target:' . $key ] : '';
            $rest = $m[1] . $m[3];
            $rest = trim( preg_replace( '/\\sdata-wpb-button-link="[^"]*"/', '', ' ' . $rest ) );
            $btn = '<button ' . $rest . '>' . $m[4] . '</button>';
            if ( $href === '' ) return $btn;
            $extra = '';
            if ( $rel !== '' )    $extra .= ' rel="'    . esc_attr( $rel )    . '"';
            if ( $target !== '' ) $extra .= ' target="' . esc_attr( $target ) . '"';
            return '<a href="' . esc_url( $href ) . '"' . $extra . '>' . $btn . '</a>';
        },
        $rendered
    ) ?? $rendered;
    // Link rel/target pass: every <a data-wpb-link="key"> gets its rel
    // and target attributes rewritten from the URL control's metadata
    // (nofollow flag → rel="nofollow", is_external flag → target="_blank"
    //  + rel="noopener noreferrer"). Drops the data-wpb-link marker on
    // its way out so it doesn't leak into the rendered page.
    $rendered = preg_replace_callback(
        '/<a\\b([^>]*?)\\sdata-wpb-link="([A-Za-z0-9_]+)"([^>]*)>/i',
        function ( $m ) use ( $attrs ) {
            $key   = $m[2];
            $rel   = isset( $attrs[ '__rel:' . $key ] )    ? (string) $attrs[ '__rel:' . $key ]    : '';
            $target = isset( $attrs[ '__target:' . $key ] ) ? (string) $attrs[ '__target:' . $key ] : '';
            $rest = $m[1] . $m[3];
            // Drop any pre-existing rel / target so we always reflect
            // the saved control values rather than the original markup.
            $rest = preg_replace( '/\\s(?:rel|target)="[^"]*"/i', '', $rest );
            $rest = trim( $rest );
            $extra = '';
            if ( $rel !== '' )    $extra .= ' rel="'    . esc_attr( $rel )    . '"';
            if ( $target !== '' ) $extra .= ' target="' . esc_attr( $target ) . '"';
            return '<a ' . $rest . $extra . '>';
        },
        $rendered
    ) ?? $rendered;
    // Icon swap pass: any <i data-wpb-icon="key"> or <span data-wpb-icon="key">
    // gets the marker stripped on its way out. When the saved ICONS
    // control points at an SVG upload (library === 'svg'), the element
    // is replaced wholesale with an <img src="..."> so the uploaded
    // glyph actually renders in the browser. Font-icon edits are
    // already taken care of by the {{ATTR:k}} substitution that
    // rewrites the element's class attribute.
    $rendered = preg_replace_callback(
        '/<(i|span)\\b([^>]*?)\\sdata-wpb-icon="([A-Za-z0-9_]+)"([^>]*?)>(.*?)<\\/\\1>/is',
        function ( $m ) use ( $attrs ) {
            $tagn = strtolower( $m[1] );
            $key  = $m[3];
            $svg  = isset( $attrs[ '__icon_svg:' . $key ] ) ? (string) $attrs[ '__icon_svg:' . $key ] : '';
            $rest = $m[2] . $m[4];
            $rest = preg_replace( '/\\sdata-wpb-icon="[^"]*"/', '', ' ' . $rest );
            // legacy_native: a data-wpb-leaf-class marker carries the
            // section's wpb-leaf-{gid} CSS hook the new native style
            // controls bind to. The user-editable ICONS control fully
            // overwrites the class attribute, so without this re-merge
            // every editor edit would silently break the scoped style
            // controls. Strip the marker after reading and force-prepend
            // the value into the rendered class attribute.
            $leaf_hook = '';
            if ( preg_match( '/\\sdata-wpb-leaf-class="([^"]+)"/', $rest, $lhm ) ) {
                $leaf_hook = $lhm[1];
                $rest = preg_replace( '/\\sdata-wpb-leaf-class="[^"]*"/', '', $rest );
            }
            if ( $leaf_hook !== '' ) {
                if ( preg_match( '/\\sclass="([^"]*)"/i', $rest, $cm2 ) ) {
                    $cur = $cm2[1];
                    if ( strpos( ' ' . $cur . ' ', ' ' . $leaf_hook . ' ' ) === false ) {
                        $merged = trim( $leaf_hook . ' ' . $cur );
                        $rest = preg_replace( '/\\sclass="[^"]*"/i', ' class="' . $merged . '"', $rest, 1 );
                    }
                } else {
                    $rest .= ' class="' . $leaf_hook . '"';
                }
            }
            $rest = trim( $rest );
            // Sibling Alt Text + Icon Link controls live at conventional
            // field keys derived from this marker's class key. Looking
            // them up here (rather than threading them through the
            // marker) keeps the data-wpb-icon attribute compact and
            // matches the contract the extractor encodes.
            $alt_key  = preg_replace( '/_icon_class$/', '_icon_alt', $key );
            $link_key = preg_replace( '/_icon_class$/', '_icon_link', $key );
            $alt_text = isset( $attrs[ $alt_key ] )  ? (string) $attrs[ $alt_key ]  : '';
            $link_url = isset( $attrs[ $link_key ] ) ? (string) $attrs[ $link_key ] : '';
            $link_rel    = isset( $attrs[ '__rel:'    . $link_key ] ) ? (string) $attrs[ '__rel:'    . $link_key ] : '';
            $link_target = isset( $attrs[ '__target:' . $link_key ] ) ? (string) $attrs[ '__target:' . $link_key ] : '';
            if ( $svg !== '' ) {
                // Preserve the original class hook so any sibling CSS
                // (sizing, color, alignment) keeps applying to the swapped
                // SVG. Drop the (now-empty) class="" emitted by the
                // {{ATTR:k}} pass — a stray empty class attribute looks
                // sloppy in the rendered HTML.
                $cls = '';
                if ( preg_match( '/\\sclass="([^"]*)"/i', ' ' . $rest, $cm ) ) $cls = trim( $cm[1] );
                $cls_attr = $cls === '' ? '' : ' class="' . esc_attr( $cls ) . '"';
                // Editor's alt wins; fall back to the icon class string
                // (a stable, descriptive default) only when blank.
                $alt_value = $alt_text !== '' ? $alt_text : $cls;
                $img = '<img src="' . esc_url( $svg ) . '" alt="' . esc_attr( $alt_value ) . '"' . $cls_attr . ' />';
                if ( $link_url !== '' ) {
                    // Mirror the button/link group's rel/target plumbing
                    // so an editor-supplied Icon Link behaves identically
                    // (nofollow + target=_blank metadata).
                    $extra = '';
                    if ( $link_rel    !== '' ) $extra .= ' rel="'    . esc_attr( $link_rel )    . '"';
                    if ( $link_target !== '' ) $extra .= ' target="' . esc_attr( $link_target ) . '"';
                    return '<a href="' . esc_url( $link_url ) . '"' . $extra . '>' . $img . '</a>';
                }
                return $img;
            }
            // Font-icon branch: the element stays an <i> / <span> but we
            // still honour the sibling Alt Text + Icon Link controls so
            // editors get the same accessibility / link affordances they
            // would have after swapping in an SVG. Alt Text becomes an
            // aria-label (with role="img" so AT actually announces it on
            // a presentational glyph). Icon Link wraps the whole element
            // in an <a>, mirroring the SVG branch's rel/target plumbing.
            $extra_attrs = '';
            if ( $alt_text !== '' ) {
                // Drop any pre-existing aria-label / role so we always
                // reflect the saved control values rather than whatever
                // the original markup carried.
                $rest = preg_replace( '/\\s(?:aria-label|role)="[^"]*"/i', '', ' ' . $rest );
                $rest = trim( $rest );
                $extra_attrs = ' role="img" aria-label="' . esc_attr( $alt_text ) . '"';
            }
            $open_attrs = ( $rest === '' ? '' : ' ' . $rest ) . $extra_attrs;
            $element = '<' . $tagn . $open_attrs . '>' . $m[5] . '</' . $tagn . '>';
            if ( $link_url !== '' ) {
                $extra = '';
                if ( $link_rel    !== '' ) $extra .= ' rel="'    . esc_attr( $link_rel )    . '"';
                if ( $link_target !== '' ) $extra .= ' target="' . esc_attr( $link_target ) . '"';
                return '<a href="' . esc_url( $link_url ) . '"' . $extra . '>' . $element . '</a>';
            }
            return $element;
        },
        $rendered
    ) ?? $rendered;
    // Heading tag-swap pass: any element marked with data-wpb-tag="key"
    // gets its open/close tag rewritten to whichever h1-h6 the saved field
    // value asks for. We only touch h1-h6 elements so other markup stays
    // intact, and we sanitise the target tag against the same allowlist.
    // The pass also reads the sibling data-wpb-heading-link marker so it
    // can wrap the heading's text content in an <a href> when the editor
    // sets a Link value (mirrors the native Heading widget's Link
    // control). The marker is always stripped on its way out.
    $rendered = preg_replace_callback(
        '/<(h[1-6])([^>]*?)\\sdata-wpb-tag="([A-Za-z0-9_]+)"([^>]*)>(.*?)<\\/\\1>/is',
        function ( $m ) use ( $attrs ) {
            $orig = $m[1];
            $key  = $m[3];
            $next = isset( $attrs[ $key ] ) && is_string( $attrs[ $key ] ) ? $attrs[ $key ] : $orig;
            if ( ! preg_match( '/^h[1-6]$/', $next ) ) $next = $orig;
            $rest_attrs = trim( $m[2] . ' ' . $m[4] );
            $rest_attrs = preg_replace( '/\\sdata-wpb-tag="[^"]*"/', '', ' ' . $rest_attrs );
            // Resolve the optional Heading Link control. The marker key
            // points at a URL field in $attrs; we also honour the
            // sibling __rel/__target plumbing the URL control writes so
            // the wrap matches button/link semantics exactly.
            $link_url = ''; $link_rel = ''; $link_target = '';
            if ( preg_match( '/\\sdata-wpb-heading-link="([A-Za-z0-9_]+)"/', $rest_attrs, $lm ) ) {
                $lkey = $lm[1];
                if ( isset( $attrs[ $lkey ] ) ) $link_url = (string) $attrs[ $lkey ];
                if ( isset( $attrs[ '__rel:'    . $lkey ] ) ) $link_rel    = (string) $attrs[ '__rel:'    . $lkey ];
                if ( isset( $attrs[ '__target:' . $lkey ] ) ) $link_target = (string) $attrs[ '__target:' . $lkey ];
                $rest_attrs = preg_replace( '/\\sdata-wpb-heading-link="[^"]*"/', '', $rest_attrs );
            }
            $rest_attrs = trim( $rest_attrs );
            $open_attrs = $rest_attrs === '' ? '' : ' ' . $rest_attrs;
            $inner = $m[5];
            if ( $link_url !== '' ) {
                $extra = '';
                if ( $link_rel    !== '' ) $extra .= ' rel="'    . esc_attr( $link_rel )    . '"';
                if ( $link_target !== '' ) $extra .= ' target="' . esc_attr( $link_target ) . '"';
                $inner = '<a href="' . esc_url( $link_url ) . '"' . $extra . '>' . $inner . '</a>';
            }
            return '<' . $next . $open_attrs . '>' . $inner . '</' . $next . '>';
        },
        $rendered
    ) ?? $rendered;
    // Final cleanup pass: strip any leftover data-wpb-leaf-class
    // markers from non-icon leaves (text, headings, lists, buttons,
    // images). Style controls bind via the matching wpb-leaf-{gid}
    // class which the extractor already added to the live class
    // attribute, so the marker is just a safety net for elements whose
    // class can be edited at runtime.
    $rendered = preg_replace( '/\\sdata-wpb-leaf-class="[^"]*"/', '', $rendered ) ?? $rendered;
    return $rendered;
}

/**
 * Register Elementor widgets when Elementor is active. Every editable
 * surface in the migrated site lives inside one of these widgets — there
 * is no Gutenberg block path.
 */
// Optional Elementor wiring overrides — registers a category etc.
if ( file_exists( WPB_THEME_DIR . '/inc/elementor-widgets.php' ) ) {
    require_once WPB_THEME_DIR . '/inc/elementor-widgets.php';
}

add_action( 'elementor/widgets/register', function ( $widgets_manager ) {
    $widgets_dir = WPB_THEME_DIR . '/widgets';
    if ( ! is_dir( $widgets_dir ) ) return;
    require_once WPB_THEME_DIR . '/widgets/_base-widget.php';
    foreach ( glob( $widgets_dir . '/widget-*.php' ) as $widget_file ) {
        require_once $widget_file;
        // Generated widget files are named widget-<safeDir>.php and the class
        // inside is WPB_Widget_<safeDir-with-dashes-replaced-by-underscores>.
        // Strip the 'widget-' prefix FIRST, then normalise.
        $base  = preg_replace( '/^widget-/', '', basename( $widget_file, '.php' ) );
        $class = 'WPB_Widget_' . preg_replace( '/[^a-zA-Z0-9_]/', '_', $base );
        if ( class_exists( $class ) ) {
            $widgets_manager->register( new $class() );
        }
    }
} );
`;

const ELEMENTOR_BASE_WIDGET = `<?php
if ( ! defined( 'ABSPATH' ) ) exit;
if ( ! class_exists( 'WPB_Widget_Base' ) && class_exists( '\\\\Elementor\\\\Widget_Base' ) ) {
class WPB_Widget_Base extends \\Elementor\\Widget_Base {
    protected $wpb_id = '';
    protected $wpb_label = '';
    protected $wpb_template_path = '';
    protected $wpb_fields = array();
    protected $wpb_groups = array();
    /**
     * When true, register a native-flavoured Elementor sidebar per group
     * (Group_Control_Typography, Text Color, Background, Border... pulled
     * from the matching native widget — Heading / Button / Image /
     * Icon List / Text Editor / Icon) scoped to the leaf's
     * 'wpb-leaf-{gid}' CSS class. Set by the per-section subclass when
     * the project's conversion mode is "legacy_native". The render path
     * stays identical to plain "legacy" mode.
     */
    protected $wpb_native_ui = false;

    public function get_name() { return 'wpb_' . $this->wpb_id; }
    public function get_title() { return $this->wpb_label; }
    public function get_icon() { return 'eicon-section'; }
    public function get_categories() { return array( 'general' ); }

    /**
     * Map our control type tag to Elementor's Controls_Manager constant.
     * Heading tag pickers use the native CHOOSE control (the same one
     * Elementor's own Heading widget exposes), and lists use REPEATER
     * so each item is editable as its own row.
     */
    private function wpb_control_type( $type ) {
        switch ( $type ) {
            case 'textarea': return \\Elementor\\Controls_Manager::TEXTAREA;
            case 'url':      return \\Elementor\\Controls_Manager::URL;
            case 'media':    return \\Elementor\\Controls_Manager::MEDIA;
            case 'choose':   return \\Elementor\\Controls_Manager::CHOOSE;
            case 'repeater': return \\Elementor\\Controls_Manager::REPEATER;
            case 'icons':    return \\Elementor\\Controls_Manager::ICONS;
            case 'text':
            default:         return \\Elementor\\Controls_Manager::TEXT;
        }
    }

    /**
     * Build the icon-toggle option set for a CHOOSE control. For heading
     * tag pickers we surface every allowed value (h1..h6) with a short
     * label; an eicon is used when one is available so the UI matches
     * the native Elementor Heading widget.
     */
    private function wpb_choose_options( $opts ) {
        $out = array();
        foreach ( $opts as $opt ) {
            $key = (string) $opt;
            $out[ $key ] = array(
                'title' => strtoupper( $key ),
                'icon'  => 'eicon-editor-' . $key,
            );
        }
        return $out;
    }

    /**
     * Resolve the CSS selector for a group's leaf element. The extractor
     * tags every leaf with a stable 'wpb-leaf-{gid}' class in
     * 'legacy_native' mode; this helper returns the Elementor-style
     * selector ({{WRAPPER}} .wpb-leaf-...) the native style controls
     * bind to. Falls back to {{WRAPPER}} when the leaf class is missing
     * so the widget never crashes on legacy upgrades.
     */
    private function wpb_leaf_selector( $g ) {
        $cls = isset( $g['leafClass'] ) && is_string( $g['leafClass'] ) && $g['leafClass'] !== ''
            ? $g['leafClass']
            : '';
        return $cls === '' ? '{{WRAPPER}}' : '{{WRAPPER}} .' . $cls;
    }

    /**
     * Add a Style-tab section for the group whose controls mirror the
     * named native Elementor widget. Each branch surfaces the most
     * visible style controls from that widget — Group_Control_Typography
     * + Text Color + Text Shadow for headings/text, plus Background /
     * Border / Border Radius / Padding for buttons, etc. All controls
     * use Elementor selectors rather than rendering inline styles, so
     * Elementor injects the CSS via its standard mechanism and the
     * original markup template stays unchanged.
     */
    private function wpb_register_native_style( $g ) {
        $native = isset( $g['nativeWidget'] ) ? (string) $g['nativeWidget'] : '';
        if ( $native === '' ) return;
        $sel       = $this->wpb_leaf_selector( $g );
        $section_id = 'wpb_grp_style_' . preg_replace( '/[^a-zA-Z0-9_]/', '_', $g['id'] ?? 'g' );
        // Per-leaf style defaults resolved from the page's cascaded CSS
        // at extraction time. Keys in this map correspond to the
        // control id suffixes registered below; missing keys mean
        // "fall back to Elementor's own default" (i.e. blank).
        $defaults = ( isset( $g['defaultStyles'] ) && is_array( $g['defaultStyles'] ) )
            ? $g['defaultStyles']
            : array();
        $this->start_controls_section( $section_id, array(
            'label' => esc_html( ( $g['label'] ?? 'Style' ) . ' — Style' ),
            'tab'   => \\Elementor\\Controls_Manager::TAB_STYLE,
        ) );
        // Alignment is universal — every native content widget surfaces
        // it under the Style tab. Map it to text-align so it lands on
        // both inline (heading/text) and block (button/image) leaves.
        $align_args = array(
            'label'     => esc_html__( 'Alignment', 'wpb' ),
            'type'      => \\Elementor\\Controls_Manager::CHOOSE,
            'options'   => array(
                'left'    => array( 'title' => esc_html__( 'Left', 'wpb' ),    'icon' => 'eicon-text-align-left' ),
                'center'  => array( 'title' => esc_html__( 'Center', 'wpb' ),  'icon' => 'eicon-text-align-center' ),
                'right'   => array( 'title' => esc_html__( 'Right', 'wpb' ),   'icon' => 'eicon-text-align-right' ),
                'justify' => array( 'title' => esc_html__( 'Justified', 'wpb' ), 'icon' => 'eicon-text-align-justify' ),
            ),
            'selectors' => array( $sel => 'text-align: {{VALUE}};' ),
        );
        if ( ! empty( $defaults['text_align'] ) && in_array( $defaults['text_align'], array( 'left', 'center', 'right', 'justify' ), true ) ) {
            $align_args['default'] = $defaults['text_align'];
        }
        $this->add_responsive_control( $g['id'] . '_native_align', $align_args );

        if ( in_array( $native, array( 'heading', 'text-editor', 'button', 'icon-list' ), true ) ) {
            // Heading-only Size preset: mirrors the native Heading
            // widget's Size control (Default/Small/Medium/Large/XL/XXL)
            // by mapping the chosen preset to a font-size declaration
            // on the leaf. Skipped for text-editor/button/icon-list
            // which don't surface this control natively.
            if ( $native === 'heading' ) {
                $this->add_control( $g['id'] . '_native_size', array(
                    'label'     => esc_html__( 'Size', 'wpb' ),
                    'type'      => \\Elementor\\Controls_Manager::SELECT,
                    'default'   => 'default',
                    'options'   => array(
                        'default' => esc_html__( 'Default', 'wpb' ),
                        'small'   => esc_html__( 'Small', 'wpb' ),
                        'medium'  => esc_html__( 'Medium', 'wpb' ),
                        'large'   => esc_html__( 'Large', 'wpb' ),
                        'xl'      => esc_html__( 'XL', 'wpb' ),
                        'xxl'     => esc_html__( 'XXL', 'wpb' ),
                    ),
                    'selectors_dictionary' => array(
                        'small'  => 'font-size: 15px;',
                        'medium' => 'font-size: 19px;',
                        'large'  => 'font-size: 29px;',
                        'xl'     => 'font-size: 39px;',
                        'xxl'    => 'font-size: 59px;',
                    ),
                    'selectors' => array( $sel => '{{VALUE}};' ),
                ) );
            }
            $color_args = array(
                'label'     => esc_html__( 'Text Color', 'wpb' ),
                'type'      => \\Elementor\\Controls_Manager::COLOR,
                'selectors' => array( $sel => 'color: {{VALUE}};' ),
            );
            if ( ! empty( $defaults['color'] ) ) $color_args['default'] = (string) $defaults['color'];
            $this->add_control( $g['id'] . '_native_color', $color_args );
            // Group_Control_Typography ships with every Elementor build
            // since 1.0, but we still guard with class_exists so a
            // missing symbol can never fatal the editor on legacy
            // installs. The defaults branch flips typography_typography
            // to "custom" (Elementor's "I have my own values" marker)
            // and seeds each subfield via fields_options.
            if ( class_exists( '\\Elementor\\Group_Control_Typography' ) ) {
                $typo_args = array(
                    'name'     => $g['id'] . '_native_typo',
                    'selector' => $sel,
                );
                if ( isset( $defaults['typography'] ) && is_array( $defaults['typography'] ) && count( $defaults['typography'] ) > 0 ) {
                    $fields_options = array( 'typography' => array( 'default' => 'custom' ) );
                    foreach ( $defaults['typography'] as $fkey => $fval ) {
                        $fields_options[ $fkey ] = array( 'default' => $fval );
                    }
                    $typo_args['fields_options'] = $fields_options;
                }
                $this->add_group_control(
                    \\Elementor\\Group_Control_Typography::get_type(),
                    $typo_args
                );
            }
            if ( class_exists( '\\Elementor\\Group_Control_Text_Shadow' ) ) {
                $this->add_group_control(
                    \\Elementor\\Group_Control_Text_Shadow::get_type(),
                    array(
                        'name'     => $g['id'] . '_native_text_shadow',
                        'selector' => $sel,
                    )
                );
            }
            // Heading-only Text Stroke + Blend Mode round out the native
            // Heading widget's Style tab. Group_Control_Text_Stroke is
            // only present in Elementor Pro, so we class_exists-guard
            // it. Blend Mode ships in core Elementor.
            if ( $native === 'heading' ) {
                if ( class_exists( '\\Elementor\\Group_Control_Text_Stroke' ) ) {
                    $this->add_group_control(
                        \\Elementor\\Group_Control_Text_Stroke::get_type(),
                        array(
                            'name'     => $g['id'] . '_native_text_stroke',
                            'selector' => $sel,
                        )
                    );
                }
                $this->add_control( $g['id'] . '_native_blend_mode', array(
                    'label'     => esc_html__( 'Blend Mode', 'wpb' ),
                    'type'      => \\Elementor\\Controls_Manager::SELECT,
                    'options'   => array(
                        ''            => esc_html__( 'Normal', 'wpb' ),
                        'multiply'    => 'Multiply',
                        'screen'      => 'Screen',
                        'overlay'     => 'Overlay',
                        'darken'      => 'Darken',
                        'lighten'     => 'Lighten',
                        'color-dodge' => 'Color Dodge',
                        'saturation'  => 'Saturation',
                        'color'       => 'Color',
                        'difference'  => 'Difference',
                        'exclusion'   => 'Exclusion',
                        'hue'         => 'Hue',
                        'luminosity'  => 'Luminosity',
                    ),
                    'selectors' => array( $sel => 'mix-blend-mode: {{VALUE}};' ),
                    'separator' => 'none',
                ) );
            }
        }

        if ( $native === 'button' ) {
            // Background — normal + hover. Mirrors the native Button
            // widget's two-state Style tab. We also add Border, Border
            // Radius and Padding which together make a button feel like
            // a real Elementor Button when edited.
            $bg_args = array(
                'label'     => esc_html__( 'Background Color', 'wpb' ),
                'type'      => \\Elementor\\Controls_Manager::COLOR,
                'selectors' => array( $sel => 'background-color: {{VALUE}};' ),
            );
            if ( ! empty( $defaults['background_color'] ) ) $bg_args['default'] = (string) $defaults['background_color'];
            $this->add_control( $g['id'] . '_native_bg', $bg_args );
            $bg_hover_args = array(
                'label'     => esc_html__( 'Background Color (Hover)', 'wpb' ),
                'type'      => \\Elementor\\Controls_Manager::COLOR,
                'selectors' => array( $sel . ':hover' => 'background-color: {{VALUE}};' ),
            );
            if ( ! empty( $defaults['background_color_hover'] ) ) $bg_hover_args['default'] = (string) $defaults['background_color_hover'];
            $this->add_control( $g['id'] . '_native_bg_hover', $bg_hover_args );
            $color_hover_args = array(
                'label'     => esc_html__( 'Text Color (Hover)', 'wpb' ),
                'type'      => \\Elementor\\Controls_Manager::COLOR,
                'selectors' => array( $sel . ':hover' => 'color: {{VALUE}};' ),
            );
            if ( ! empty( $defaults['color_hover'] ) ) $color_hover_args['default'] = (string) $defaults['color_hover'];
            $this->add_control( $g['id'] . '_native_color_hover', $color_hover_args );
            if ( class_exists( '\\Elementor\\Group_Control_Border' ) ) {
                $border_args = array(
                    'name'     => $g['id'] . '_native_border',
                    'selector' => $sel,
                );
                if ( isset( $defaults['border'] ) && is_array( $defaults['border'] ) ) {
                    $bf = array( 'border' => array( 'default' => isset( $defaults['border']['border'] ) ? (string) $defaults['border']['border'] : 'solid' ) );
                    if ( isset( $defaults['border']['width'] ) && is_array( $defaults['border']['width'] ) ) {
                        $bf['width'] = array( 'default' => $defaults['border']['width'] );
                    }
                    if ( ! empty( $defaults['border']['color'] ) ) {
                        $bf['color'] = array( 'default' => (string) $defaults['border']['color'] );
                    }
                    $border_args['fields_options'] = $bf;
                }
                $this->add_group_control(
                    \\Elementor\\Group_Control_Border::get_type(),
                    $border_args
                );
            }
            $radius_args = array(
                'label'      => esc_html__( 'Border Radius', 'wpb' ),
                'type'       => \\Elementor\\Controls_Manager::DIMENSIONS,
                'size_units' => array( 'px', '%', 'em' ),
                'selectors'  => array( $sel => 'border-radius: {{TOP}}{{UNIT}} {{RIGHT}}{{UNIT}} {{BOTTOM}}{{UNIT}} {{LEFT}}{{UNIT}};' ),
            );
            if ( isset( $defaults['border_radius'] ) && is_array( $defaults['border_radius'] ) ) {
                $radius_args['default'] = $defaults['border_radius'];
            }
            $this->add_responsive_control( $g['id'] . '_native_radius', $radius_args );
            $padding_args = array(
                'label'      => esc_html__( 'Padding', 'wpb' ),
                'type'       => \\Elementor\\Controls_Manager::DIMENSIONS,
                'size_units' => array( 'px', '%', 'em' ),
                'selectors'  => array( $sel => 'padding: {{TOP}}{{UNIT}} {{RIGHT}}{{UNIT}} {{BOTTOM}}{{UNIT}} {{LEFT}}{{UNIT}};' ),
            );
            if ( isset( $defaults['padding'] ) && is_array( $defaults['padding'] ) ) {
                $padding_args['default'] = $defaults['padding'];
            }
            $this->add_responsive_control( $g['id'] . '_native_padding', $padding_args );
            // Hover-state mirrors of Border / Border Radius / Padding /
            // Typography. Many real-world CTAs change more than just
            // background+text colour on hover (e.g. border-color flip,
            // padding nudge, font-weight bump). Surfacing them as
            // dedicated controls — pre-populated from the source page's
            // :hover declarations — keeps the visible effect intact when
            // the customer touches an unrelated control.
            if ( class_exists( '\\Elementor\\Group_Control_Border' ) ) {
                $border_hover_args = array(
                    'name'     => $g['id'] . '_native_border_hover',
                    'selector' => $sel . ':hover',
                );
                if ( isset( $defaults['border_hover'] ) && is_array( $defaults['border_hover'] ) ) {
                    $bhf = array( 'border' => array( 'default' => isset( $defaults['border_hover']['border'] ) ? (string) $defaults['border_hover']['border'] : 'solid' ) );
                    if ( isset( $defaults['border_hover']['width'] ) && is_array( $defaults['border_hover']['width'] ) ) {
                        $bhf['width'] = array( 'default' => $defaults['border_hover']['width'] );
                    }
                    if ( ! empty( $defaults['border_hover']['color'] ) ) {
                        $bhf['color'] = array( 'default' => (string) $defaults['border_hover']['color'] );
                    }
                    $border_hover_args['fields_options'] = $bhf;
                }
                $this->add_group_control(
                    \\Elementor\\Group_Control_Border::get_type(),
                    $border_hover_args
                );
            }
            $radius_hover_args = array(
                'label'      => esc_html__( 'Border Radius (Hover)', 'wpb' ),
                'type'       => \\Elementor\\Controls_Manager::DIMENSIONS,
                'size_units' => array( 'px', '%', 'em' ),
                'selectors'  => array( $sel . ':hover' => 'border-radius: {{TOP}}{{UNIT}} {{RIGHT}}{{UNIT}} {{BOTTOM}}{{UNIT}} {{LEFT}}{{UNIT}};' ),
            );
            if ( isset( $defaults['border_radius_hover'] ) && is_array( $defaults['border_radius_hover'] ) ) {
                $radius_hover_args['default'] = $defaults['border_radius_hover'];
            }
            $this->add_responsive_control( $g['id'] . '_native_radius_hover', $radius_hover_args );
            $padding_hover_args = array(
                'label'      => esc_html__( 'Padding (Hover)', 'wpb' ),
                'type'       => \\Elementor\\Controls_Manager::DIMENSIONS,
                'size_units' => array( 'px', '%', 'em' ),
                'selectors'  => array( $sel . ':hover' => 'padding: {{TOP}}{{UNIT}} {{RIGHT}}{{UNIT}} {{BOTTOM}}{{UNIT}} {{LEFT}}{{UNIT}};' ),
            );
            if ( isset( $defaults['padding_hover'] ) && is_array( $defaults['padding_hover'] ) ) {
                $padding_hover_args['default'] = $defaults['padding_hover'];
            }
            $this->add_responsive_control( $g['id'] . '_native_padding_hover', $padding_hover_args );
            if ( class_exists( '\\Elementor\\Group_Control_Typography' ) ) {
                $typo_hover_args = array(
                    'name'     => $g['id'] . '_native_typo_hover',
                    'selector' => $sel . ':hover',
                );
                if ( isset( $defaults['typography_hover'] ) && is_array( $defaults['typography_hover'] ) && count( $defaults['typography_hover'] ) > 0 ) {
                    $fields_options = array( 'typography' => array( 'default' => 'custom' ) );
                    foreach ( $defaults['typography_hover'] as $fkey => $fval ) {
                        $fields_options[ $fkey ] = array( 'default' => $fval );
                    }
                    $typo_hover_args['fields_options'] = $fields_options;
                }
                $this->add_group_control(
                    \\Elementor\\Group_Control_Typography::get_type(),
                    $typo_hover_args
                );
            }
        }

        if ( $native === 'image' ) {
            $width_args = array(
                'label'      => esc_html__( 'Width', 'wpb' ),
                'type'       => \\Elementor\\Controls_Manager::SLIDER,
                'size_units' => array( 'px', '%', 'vw' ),
                'range'      => array(
                    'px' => array( 'min' => 0, 'max' => 1600 ),
                    '%'  => array( 'min' => 0, 'max' => 100 ),
                ),
                'selectors'  => array( $sel => 'width: {{SIZE}}{{UNIT}}; height: auto;' ),
            );
            if ( isset( $defaults['width'] ) && is_array( $defaults['width'] ) ) $width_args['default'] = $defaults['width'];
            $this->add_responsive_control( $g['id'] . '_native_width', $width_args );
            $maxw_args = array(
                'label'      => esc_html__( 'Max Width', 'wpb' ),
                'type'       => \\Elementor\\Controls_Manager::SLIDER,
                'size_units' => array( 'px', '%' ),
                'range'      => array( 'px' => array( 'min' => 0, 'max' => 1600 ) ),
                'selectors'  => array( $sel => 'max-width: {{SIZE}}{{UNIT}};' ),
            );
            if ( isset( $defaults['max_width'] ) && is_array( $defaults['max_width'] ) ) $maxw_args['default'] = $defaults['max_width'];
            $this->add_responsive_control( $g['id'] . '_native_max_width', $maxw_args );
            $this->add_control( $g['id'] . '_native_opacity', array(
                'label'      => esc_html__( 'Opacity', 'wpb' ),
                'type'       => \\Elementor\\Controls_Manager::SLIDER,
                'range'      => array( 'px' => array( 'min' => 0, 'max' => 1, 'step' => 0.05 ) ),
                'selectors'  => array( $sel => 'opacity: {{SIZE}};' ),
            ) );
            if ( class_exists( '\\Elementor\\Group_Control_Border' ) ) {
                $img_border_args = array(
                    'name'     => $g['id'] . '_native_border',
                    'selector' => $sel,
                );
                if ( isset( $defaults['border'] ) && is_array( $defaults['border'] ) ) {
                    $bf = array( 'border' => array( 'default' => isset( $defaults['border']['border'] ) ? (string) $defaults['border']['border'] : 'solid' ) );
                    if ( isset( $defaults['border']['width'] ) && is_array( $defaults['border']['width'] ) ) {
                        $bf['width'] = array( 'default' => $defaults['border']['width'] );
                    }
                    if ( ! empty( $defaults['border']['color'] ) ) {
                        $bf['color'] = array( 'default' => (string) $defaults['border']['color'] );
                    }
                    $img_border_args['fields_options'] = $bf;
                }
                $this->add_group_control(
                    \\Elementor\\Group_Control_Border::get_type(),
                    $img_border_args
                );
            }
            $img_radius_args = array(
                'label'      => esc_html__( 'Border Radius', 'wpb' ),
                'type'       => \\Elementor\\Controls_Manager::DIMENSIONS,
                'size_units' => array( 'px', '%' ),
                'selectors'  => array( $sel => 'border-radius: {{TOP}}{{UNIT}} {{RIGHT}}{{UNIT}} {{BOTTOM}}{{UNIT}} {{LEFT}}{{UNIT}};' ),
            );
            if ( isset( $defaults['border_radius'] ) && is_array( $defaults['border_radius'] ) ) $img_radius_args['default'] = $defaults['border_radius'];
            $this->add_responsive_control( $g['id'] . '_native_radius', $img_radius_args );
        }

        if ( $native === 'icon' ) {
            $icon_color_args = array(
                'label'     => esc_html__( 'Icon Color', 'wpb' ),
                'type'      => \\Elementor\\Controls_Manager::COLOR,
                'selectors' => array( $sel => 'color: {{VALUE}}; fill: {{VALUE}};' ),
            );
            if ( ! empty( $defaults['color'] ) ) $icon_color_args['default'] = (string) $defaults['color'];
            $this->add_control( $g['id'] . '_native_icon_color', $icon_color_args );
            $icon_color_hover_args = array(
                'label'     => esc_html__( 'Icon Color (Hover)', 'wpb' ),
                'type'      => \\Elementor\\Controls_Manager::COLOR,
                'selectors' => array( $sel . ':hover' => 'color: {{VALUE}}; fill: {{VALUE}};' ),
            );
            if ( ! empty( $defaults['color_hover'] ) ) $icon_color_hover_args['default'] = (string) $defaults['color_hover'];
            $this->add_control( $g['id'] . '_native_icon_color_hover', $icon_color_hover_args );
            $icon_size_args = array(
                'label'      => esc_html__( 'Size', 'wpb' ),
                'type'       => \\Elementor\\Controls_Manager::SLIDER,
                'size_units' => array( 'px', 'em' ),
                'range'      => array( 'px' => array( 'min' => 6, 'max' => 300 ) ),
                'selectors'  => array( $sel => 'font-size: {{SIZE}}{{UNIT}};' ),
            );
            if ( isset( $defaults['icon_size'] ) && is_array( $defaults['icon_size'] ) ) $icon_size_args['default'] = $defaults['icon_size'];
            $this->add_responsive_control( $g['id'] . '_native_icon_size', $icon_size_args );
            $icon_pad_args = array(
                'label'      => esc_html__( 'Padding', 'wpb' ),
                'type'       => \\Elementor\\Controls_Manager::DIMENSIONS,
                'size_units' => array( 'px', '%', 'em' ),
                'selectors'  => array( $sel => 'padding: {{TOP}}{{UNIT}} {{RIGHT}}{{UNIT}} {{BOTTOM}}{{UNIT}} {{LEFT}}{{UNIT}};' ),
            );
            if ( isset( $defaults['padding'] ) && is_array( $defaults['padding'] ) ) $icon_pad_args['default'] = $defaults['padding'];
            $this->add_responsive_control( $g['id'] . '_native_icon_padding', $icon_pad_args );
        }

        $this->end_controls_section();
    }

    protected function register_controls() {
        // Preferred path: walk the semantic groups[] and emit one
        // start_controls_section per element (Button, Image, Heading...).
        // Falls back to the old flat fields[] list when groups are empty
        // (legacy theme upgrade path).
        if ( is_array( $this->wpb_groups ) && count( $this->wpb_groups ) > 0 ) {
            foreach ( $this->wpb_groups as $g ) {
                $section_id = 'wpb_grp_' . preg_replace( '/[^a-zA-Z0-9_]/', '_', $g['id'] ?? 'g' );
                $this->start_controls_section( $section_id, array(
                    'label' => esc_html( $g['label'] ?? 'Section' ),
                    'tab'   => \\Elementor\\Controls_Manager::TAB_CONTENT,
                ) );
                foreach ( ($g['controls'] ?? array()) as $c ) {
                    $type = $this->wpb_control_type( $c['type'] ?? 'text' );
                    $args = array(
                        'label'       => esc_html( $c['label'] ?? $c['key'] ),
                        'type'        => $type,
                        'label_block' => true,
                    );
                    if ( $type === \\Elementor\\Controls_Manager::URL ) {
                        $args['default'] = array(
                            'url'         => $c['default'] ?? '',
                            'is_external' => false,
                            'nofollow'    => false,
                        );
                    } elseif ( $type === \\Elementor\\Controls_Manager::MEDIA ) {
                        $args['default'] = array(
                            'url' => $c['default'] ?? '',
                        );
                    } elseif ( $type === \\Elementor\\Controls_Manager::ICONS ) {
                        // ICONS control: default value carries the
                        // original icon-font class string and we tag it
                        // as a Font Awesome library entry. Customers can
                        // also swap to an SVG upload via the attached
                        // MEDIA picker — that case is handled by the
                        // wpb_settings_to_attrs reduction at render time.
                        $args['default'] = array(
                            'value'   => $c['default'] ?? '',
                            'library' => 'fa-solid',
                        );
                    } elseif ( $type === \\Elementor\\Controls_Manager::CHOOSE ) {
                        $opts = isset( $c['options'] ) && is_array( $c['options'] ) ? $c['options'] : array();
                        $args['options']     = $this->wpb_choose_options( $opts );
                        $args['default']     = $c['default'] ?? ( $opts[0] ?? '' );
                        $args['toggle']      = false;
                    } elseif ( $type === \\Elementor\\Controls_Manager::REPEATER ) {
                        // Build a single-field repeater: each row carries an
                        // "item" TEXT field that maps back to one <li>.
                        // Defaults are seeded from the textarea-style
                        // newline-joined string the extractor stored.
                        $repeater = new \\Elementor\\Repeater();
                        $repeater->add_control( 'item', array(
                            'label'       => esc_html__( 'Item', 'wpb' ),
                            'type'        => \\Elementor\\Controls_Manager::TEXT,
                            'default'     => '',
                            'label_block' => true,
                        ) );
                        $args['fields']  = $repeater->get_controls();
                        $args['default'] = array();
                        $seed = is_string( $c['default'] ?? '' ) ? (string) $c['default'] : '';
                        if ( $seed !== '' ) {
                            foreach ( preg_split( '/\\r?\\n/', $seed ) as $row ) {
                                $row = trim( $row );
                                if ( $row === '' ) continue;
                                $args['default'][] = array( 'item' => $row );
                            }
                        }
                        $args['title_field'] = '{{{ item }}}';
                    } else {
                        $args['default'] = $c['default'] ?? '';
                    }
                    $this->add_control( $c['key'], $args );
                }
                $this->end_controls_section();
                // legacy_native: tack a Style-tab section onto every
                // group whose controls mirror the matching native
                // Elementor widget (Group_Control_Typography + Text
                // Color + Border / Background for buttons, etc.). The
                // controls bind to {{WRAPPER}} .wpb-leaf-{gid} so the
                // edits land on the original markup wrapper without
                // changing the render path.
                if ( $this->wpb_native_ui ) {
                    $this->wpb_register_native_style( $g );
                }
            }
            return;
        }

        $this->start_controls_section( 'content', array(
            'label' => esc_html__( 'Content', 'wpb' ),
            'tab'   => \\Elementor\\Controls_Manager::TAB_CONTENT,
        ) );
        foreach ( $this->wpb_fields as $f ) {
            $type = $f['type'] === 'text' && strlen( $f['default'] ?? '' ) > 80
                ? \\Elementor\\Controls_Manager::TEXTAREA
                : \\Elementor\\Controls_Manager::TEXT;
            $this->add_control( $f['key'], array(
                'label'   => esc_html( $f['label'] ?? $f['key'] ),
                'type'    => $type,
                'default' => $f['default'] ?? '',
            ) );
        }
        $this->end_controls_section();
    }

    /**
     * Reduce the Elementor settings array (which uses structured shapes
     * for URL / MEDIA controls) down to the flat scalar map the template
     * renderer expects. Each control's value lands at $attrs[$fieldKey],
     * keyed by whatever placeholder ({{TEXT:k}}, {{URL:k}}, ...) the
     * template uses.
     */
    private function wpb_settings_to_attrs( $settings ) {
        $attrs = array();
        if ( ! is_array( $this->wpb_groups ) ) return $settings;
        foreach ( $this->wpb_groups as $g ) {
            foreach ( ($g['controls'] ?? array()) as $c ) {
                $ck  = $c['key'] ?? '';
                $fk  = $c['fieldKey'] ?? $ck;
                $val = $settings[ $ck ] ?? ( $c['default'] ?? '' );
                $type = $c['type'] ?? 'text';
                if ( $type === 'url' && is_array( $val ) ) {
                    // Capture the URL control's rel/target metadata so the
                    // post-render pass can stamp them back onto any
                    // <a data-wpb-link="<key>"> element. Two synthetic
                    // attrs keys are used so they can never collide with
                    // a real placeholder name (placeholders are matched
                    // against [A-Za-z0-9_]+ only).
                    $is_external = ! empty( $val['is_external'] );
                    $nofollow    = ! empty( $val['nofollow'] );
                    $rel_parts = array();
                    if ( $nofollow )    $rel_parts[] = 'nofollow';
                    if ( $is_external ) { $rel_parts[] = 'noopener'; $rel_parts[] = 'noreferrer'; }
                    $attrs[ '__rel:'    . $ck ] = implode( ' ', array_unique( $rel_parts ) );
                    $attrs[ '__target:' . $ck ] = $is_external ? '_blank' : '';
                    $val = isset( $val['url'] ) ? (string) $val['url'] : '';
                } elseif ( $type === 'icons' && is_array( $val ) ) {
                    // ICONS control: shape is { value, library }. For
                    // font icons (library != 'svg'), value is the class
                    // string and we surface it as the icon's class via
                    // the {{ATTR:k}} substitution. For SVG uploads, the
                    // value is itself { id, url } — we stash the URL on
                    // a synthetic attrs key (__icon_svg:<key>) so the
                    // post-render pass can swap the <i>/<span> for an
                    // <img src="..."> with the uploaded SVG.
                    $library = isset( $val['library'] ) ? (string) $val['library'] : '';
                    $iv      = $val['value'] ?? '';
                    if ( $library === 'svg' && is_array( $iv ) ) {
                        $svg_url = isset( $iv['url'] ) ? (string) $iv['url'] : '';
                        $attrs[ '__icon_svg:' . $ck ] = $svg_url;
                        $val = '';
                    } else {
                        $val = is_string( $iv ) ? $iv : (string) $iv;
                    }
                } elseif ( $type === 'media' && is_array( $val ) ) {
                    // Capture the attachment id alongside the URL so the
                    // post-render image pass can swap a plain <img> for
                    // wp_get_attachment_image() (which emits proper
                    // srcset/sizes) when the user picks an image from
                    // the WordPress media library.
                    $attrs[ '__media_id:' . $ck ] = isset( $val['id'] ) ? (int) $val['id'] : 0;
                    $val = isset( $val['url'] ) ? (string) $val['url'] : '';
                } elseif ( $type === 'repeater' && is_array( $val ) ) {
                    // Collapse the repeater rows back into the
                    // newline-joined text the {{LIST:k}} renderer
                    // expects. Each row is either an associative
                    // array with an "item" field or, defensively, a
                    // bare scalar.
                    $rows = array();
                    foreach ( $val as $row ) {
                        if ( is_array( $row ) ) {
                            $item = isset( $row['item'] ) ? (string) $row['item'] : '';
                        } else {
                            $item = (string) $row;
                        }
                        $item = trim( $item );
                        if ( $item !== '' ) $rows[] = $item;
                    }
                    $val = implode( "\\n", $rows );
                } else {
                    $val = is_string( $val ) ? $val : (string) $val;
                }
                $attrs[ $fk ] = $val;
            }
        }
        return $attrs;
    }

    protected function render() {
        $settings = $this->get_settings_for_display();
        $attrs    = is_array( $this->wpb_groups ) && count( $this->wpb_groups ) > 0
            ? $this->wpb_settings_to_attrs( $settings )
            : $settings;
        echo wpb_render_section_template( WPB_THEME_DIR . '/' . $this->wpb_template_path, $attrs );
    }
}
}
`;

function widgetPhpFor(section: ExtractedSection, templateRelPath: string, nativeUi: boolean): string {
  const safeId = section.blockName.split("/")[1].replace(/[^a-zA-Z0-9_]/g, "_");
  const fieldsJson = JSON.stringify(section.fields).replace(/'/g, "\\'");
  const groupsJson = JSON.stringify(section.groups ?? []).replace(/'/g, "\\'");
  return `<?php
if ( ! defined( 'ABSPATH' ) ) exit;
if ( ! class_exists( 'WPB_Widget_Base' ) ) return;
class WPB_Widget_${safeId} extends WPB_Widget_Base {
    public function __construct( $data = array(), $args = null ) {
        $this->wpb_id = '${safeId}';
        $this->wpb_label = ${JSON.stringify(section.label)};
        $this->wpb_template_path = ${JSON.stringify(templateRelPath)};
        $this->wpb_fields = json_decode( '${fieldsJson}', true ) ?: array();
        $this->wpb_groups = json_decode( '${groupsJson}', true ) ?: array();
        $this->wpb_native_ui = ${nativeUi ? "true" : "false"};
        parent::__construct( $data, $args );
    }
}
`;
}

const ASSET_EXT = new Set(["png", "jpg", "jpeg", "gif", "webp", "avif", "svg", "ico", "woff", "woff2", "ttf", "otf", "eot"]);

/**
 * Build a complete WordPress child theme ZIP. The ZIP lives under a single
 * top-level folder named `${projectSlug}` so it can be uploaded directly
 * via Appearance → Themes → Add New → Upload.
 */
export function generateThemeZip(input: ThemeInput): Buffer {
  const { projectSlug, projectName, combinedCss, combinedJs, pages, sourceZip } = input;
  const nativeUi = input.conversionMode === "legacy_native";
  const zip = new AdmZip();
  const root = projectSlug;

  zip.addFile(`${root}/style.css`, Buffer.from(STYLE_HEADER(projectName, projectSlug) + "\n" + combinedCss, "utf8"));
  zip.addFile(`${root}/index.php`, Buffer.from(INDEX_PHP, "utf8"));
  zip.addFile(`${root}/page.php`, Buffer.from(PAGE_PHP, "utf8"));
  zip.addFile(`${root}/header.php`, Buffer.from(HEADER_PHP, "utf8"));
  zip.addFile(`${root}/footer.php`, Buffer.from(FOOTER_PHP, "utf8"));
  zip.addFile(`${root}/inc/elementor-widgets.php`, Buffer.from(ELEMENTOR_WIDGETS_INC, "utf8"));
  zip.addFile(`${root}/assets/template.css`, Buffer.from(combinedCss, "utf8"));
  if (combinedJs.trim().length > 0) {
    zip.addFile(`${root}/assets/template.js`, Buffer.from(combinedJs, "utf8"));
  }
  zip.addFile(`${root}/widgets/_base-widget.php`, Buffer.from(ELEMENTOR_BASE_WIDGET, "utf8"));

  const allBlockNames: string[] = [];
  const seen = new Set<string>();
  for (const page of pages) {
    for (const section of page.sections) {
      if (seen.has(section.blockName)) continue;
      seen.add(section.blockName);
      // Sections that ship as a native Elementor `section → column → widget`
      // tree don't need a PHP widget class — Elementor's built-in widgets
      // (heading / image / button / icon / icon-list / text-editor / html)
      // render them directly. Skip the per-section PHP file and template.
      if (section.nativeElementor) continue;
      allBlockNames.push(section.blockName);
      const safeDir = section.blockName.split("/")[1];
      // Templates live under widgets/templates/<safeDir>/template.html so the
      // theme has no Gutenberg block infrastructure (no blocks/ dir, no
      // block.json, no editor.js). The Elementor widget loads the template
      // via wpb_render_section_template().
      const tplRel = `widgets/templates/${safeDir}/template.html`;
      zip.addFile(`${root}/${tplRel}`, Buffer.from(section.template, "utf8"));
      zip.addFile(`${root}/widgets/widget-${safeDir}.php`, Buffer.from(widgetPhpFor(section, tplRel, nativeUi), "utf8"));
    }
  }

  zip.addFile(`${root}/functions.php`, Buffer.from(FUNCTIONS_PHP_TEMPLATE(projectSlug, allBlockNames), "utf8"));

  // Copy original images + fonts into assets/ so paths resolve identically.
  if (sourceZip) {
    try {
      const src = new AdmZip(sourceZip);
      for (const e of src.getEntries()) {
        if (e.isDirectory) continue;
        const name = e.entryName.replace(/\\/g, "/");
        if (name.startsWith("__MACOSX/") || name.includes("/.DS_Store")) continue;
        const ext = name.split(".").pop()?.toLowerCase() ?? "";
        if (!ASSET_EXT.has(ext)) continue;
        zip.addFile(`${root}/assets/${name}`, e.getData());
      }
    } catch {
      // Original ZIP missing or corrupt — skip the asset bundle (the theme
      // still renders, just with broken local image refs).
    }
  }

  const readme = `# ${projectName} (Pixel-Perfect Theme)

Generated by WP Bridge AI. Upload via WordPress → Appearance → Themes → Add New → Upload Theme. Activate.

Each section of the original site is registered as a native Elementor widget with semantic controls (button, link, image, heading, text, list). Edit content inside Elementor — the original CSS/JS keeps the design pixel-perfect.
`;
  zip.addFile(`${root}/README.md`, Buffer.from(readme, "utf8"));

  return zip.toBuffer();
}
